### PR TITLE
[dim] Class overriding interface method that was already override by another interface

### LINKED ISSUE #18917: Explicit interface property ignored when there is a default implementation
## Steps to Reproduce

When running a xamarin app, I was getting a crash with the following message:
```
02-18 18:34:34.760 F/        ( 7136): * Assertion: should not be reached at /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/mono/mini/mini-trampolines.c:590
02-18 18:34:34.760 F/libc    ( 7136): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 7136 (rmmodel.android), pid 7136 (rmmodel.android)
```

The crash stopped when I removed a default interface property. When trying to isolate the issue, I found the following, possibly related issue. With the following class structure:

```csharp
public interface IInterface
{
	IConvertible Value { get; }
}

public interface IInterface<T> : IInterface where T : IConvertible
{
	new T Value { get; }

	IConvertible IInterface.Value => 56;
}

public abstract class AbstractClass : IInterface
{
	IConvertible IInterface.Value => GetValueInternal();

	internal abstract IConvertible GetValueInternal();
}

public abstract class AbstractClass<T> : AbstractClass, IInterface<T> where T : IConvertible
{
	T IInterface<T>.Value => GetValue();

	protected abstract T GetValue();

	internal sealed override IConvertible GetValueInternal() => GetValue();
}

public class Class<T> : AbstractClass<T>, IInterface<T> where T : IConvertible
{
	private T _value;

	public T Value
	{
		get => _value;
		set => _value = value;
	}

	protected override T GetValue() => _value;
}
```

Call this code:

```
var var0 = new Class<int> { Value = 55 };
var var1 = var0.Value;
var var2 = (Test.IInterface)var0;
var var3 = var2.Value;
```

### Expected Behavior

when getting var3, the explicit implementation of IInterface on AbstractClass will be called and 55 will be returned. This happens on a .net core console app.

### Current Behavior

The default implementation is called, and 56 is returned

## On which platforms did you notice this

Android

**Version Used**:

v4.0.30319

### PR DESCRIPTION
**Pull request by thaystg**
The problem was a parent class overriding an interface that was already override by another interface.

Fix #18917

### CODE REVIEW

**Comment by thaystg** [comment]
monojenkins build Linux ARMv7

**Comment by thaystg** [comment]
@monojenkins build Linux ARMv7

File: mono/metadata/class-init.c [hunk 1]
```diff
@@ -2855,41 +2860,18 @@ print_vtable_layout_result (MonoClass *klass, MonoMethod **vtable, int cur_slot)
...
 	}
 }
-
-/*
- * LOCKING: this is supposed to be called with the loader lock held.
- */
-void
-mono_class_setup_vtable_general (MonoClass *klass, MonoMethod **overrides, int onum, GList *in_setup)
+static int 
+setup_class_vtsize (MonoClass *klass, GList *in_setup, int *cur_slot, int *stelemref_slot, MonoError *error)
```
Comment (lambdageek) [inline mono/metadata/class-init.c]: suggestion: add a `/* LOCKING */` comment

File: mono/metadata/class-init.c [hunk 2]
```diff
@@ -2904,105 +2886,114 @@ mono_class_setup_vtable_general (MonoClass *klass, MonoMethod **overrides, int o
...
 		++max_vtsize;
-		++cur_slot;
+		++*cur_slot;
 	}
+	return max_vtsize;
+}
 
-	/* printf ("METAINIT %s.%s\n", klass->name_space, klass->name); */
+static int
+mono_class_setup_vtable_ginst (MonoClass *klass, GList *in_setup, MonoError *error)
```
Comment (lambdageek) [inline mono/metadata/class-init.c]: 1. return a `gboolean` instead of `int`
2. `/* LOCKING */` comment
3. comment like `/* returns FALSE and sets MonoError if setup fails */ `

but also this method is pretty weird because sometimes it returns "success" but really the `klass` is already marked with a failure.

I wonder if it should just have a local `MonoError` and do its own `fail` case and just always return (ie you won't need the `goto fail` code in the caller)

File: mono/metadata/class-init.c [hunk 3]
```diff
@@ -3017,34 +3008,6 @@ mono_class_setup_vtable_general (MonoClass *klass, MonoMethod **overrides, int o
...
-				mono_error_assert_ok (error);
-			} else if (mono_class_is_gtd (override->klass)) {
-				override = mono_class_inflate_generic_method_full_checked (override, ic, mono_class_get_context (ic), error);
-			}
-			if (!apply_override (klass, ic, vtable, decl, override, &override_map, &override_class_map, &conflict_map))
-				goto fail;
-		}
-		g_free (iface_overrides);
-	}
-
```
Comment (lambdageek) [inline mono/metadata/class-init.c]: I don't understand why it's ok to move this later after the `/* override interface methods */` `for`-loop.  Doesn't that change which overrides get used?

Comment (thaystg) [reply mono/metadata/class-init.c]: Yes, I think so, I just change to check if this would break any test. I think I should try to create a test that tests it.

File: mono/metadata/class-init.c [hunk 4]
```diff
@@ -2904,105 +2890,120 @@ mono_class_setup_vtable_general (MonoClass *klass, MonoMethod **overrides, int o
...
-			}
-		mono_memory_barrier ();
-		klass->vtable = tmp;
+	if (mono_print_vtable)
+		print_vtable_layout_result (klass, klass->vtable, gklass->vtable_size);
 
-		mono_loader_lock ();
-		klass->has_dim_conflicts = gklass->has_dim_conflicts;
-		mono_loader_unlock ();
+	return;
```
Comment (lambdageek) [inline mono/metadata/class-init.c]:
```suggestion
```

File: mono/metadata/class-init.c [hunk 5]
```diff
@@ -3393,7 +3394,7 @@ mono_class_setup_vtable_general (MonoClass *klass, MonoMethod **overrides, int o
 	char *name = mono_type_get_full_name (klass);
 	if (!is_ok (error))
 		mono_class_set_type_load_failure (klass, "VTable setup of type %s failed due to: %s", name, mono_error_get_message (error));
-	else
+	elseƒ
```
Comment (lambdageek) [inline mono/metadata/class-init.c]:
```suggestion
	else
```

**Comment by lambdageek** [comment]
@monojenkins backport to 2020-02
