### PR TITLE
[debugger] Don't list finalizer gc thread if it's not executing managed code

### LINKED ISSUE #13311: [sdb] Failure to suspend
Unzip the following repro:

[reprosdb2.zip](https://github.com/mono/mono/files/2931889/reprosdb2.zip)

`build.sh && mono debugger.exe`

This doesn't repro all the time, so it might be timing related, but sometimes you get:

```
lemacbook:reprosdb2 jbevain$ mono debugger.exe 
Launching debuggee.exe
Resuming debuggee.exe
Hello
Suspending debuggee.exe
Finding Program
Finding Program::Greeting
Finding Program::Stop
Invoking Program::Greeting
Exception: Mono.Debugger.Soft.VMNotSuspendedException: The vm is not suspended.
  at Mono.Debugger.Soft.VirtualMachine.ErrorHandler (System.Object sender, Mono.Debugger.Soft.ErrorHandlerEventArgs args) [0x00049] in <133d7a00f5834ce18a336603a1b450a2>:0 
  at Mono.Debugger.Soft.ObjectMirror.EndInvokeMethodInternalWithResult (System.IAsyncResult asyncResult) [0x00049] in <133d7a00f5834ce18a336603a1b450a2>:0 
  at Mono.Debugger.Soft.ObjectMirror.EndInvokeMethodInternal (System.IAsyncResult asyncResult) [0x00000] in <133d7a00f5834ce18a336603a1b450a2>:0 
  at Mono.Debugger.Soft.ObjectMirror.InvokeMethod (Mono.Debugger.Soft.VirtualMachine vm, Mono.Debugger.Soft.ThreadMirror thread, Mono.Debugger.Soft.MethodMirror method, Mono.Debugger.Soft.Value this_obj, System.Collections.Generic.IList`1[T] arguments, Mono.Debugger.Soft.InvokeOptions options) [0x0000f] in <133d7a00f5834ce18a336603a1b450a2>:0 
  at Mono.Debugger.Soft.TypeMirror.InvokeMethod (Mono.Debugger.Soft.ThreadMirror thread, Mono.Debugger.Soft.MethodMirror method, System.Collections.Generic.IList`1[T] arguments) [0x00000] in <133d7a00f5834ce18a336603a1b450a2>:0 
  at Program.Main () [0x0012d] in <bbc99def2ffc435eb06c2bedfc76b769>:0 
Bye
```

And sometimes it works:

```
lemacbook:reprosdb2 jbevain$ mono debugger.exe 
Launching debuggee.exe
Resuming debuggee.exe
Hello
Suspending debuggee.exe
Finding Program
Finding Program::Greeting
Finding Program::Stop
Invoking Program::Greeting
Greeting: Hello debugger
Invoking Program::Stop
Resuming debuggee.exe
Goodbye
Bye
```

Seeing the same behavior on Windows. This impacts the VSTU CI.

### PR DESCRIPTION
**Pull request by thaystg**
The example that reproduces the bug does this:
var thread = vm.GetThreads()[0];
greetingValue = program.InvokeMethod(thread, greeting, new Value[0]) as StringMirror;

But sometimes the Thread[0] was the MainThread of the program and it works, and other times was the GC Finalizer, but when it tries to run something on GC Finalizer thread, the thread is not suspended and throws an exception.
In the fix I removed the Finalizer thread of the list that is returned when CMD_VM_ALL_THREADS is called if the thread is not executing a managed code.

Fixes #13311

### CODE REVIEW

**Comment by thaystg** [comment]
@monojenkins build failed

File: mono/mini/debugger-agent.c [hunk 1]
```diff
@@ -6009,12 +6011,43 @@ clear_types_for_assembly (MonoAssembly *assembly)
...
+	gboolean *ret = (gboolean *)remove_finalizer;
+	MonoThread *thread = (MonoThread *)value;
+	if (mono_gc_is_finalizer_internal_thread(thread->internal_thread)) {
+		DebuggerTlsData *tls = (DebuggerTlsData *)mono_g_hash_table_lookup (thread_to_tls, thread->internal_thread);
+		if (tls->frame_count == 0) {
+			*ret = TRUE;
+			return;
+		}
+		if (tls->frame_count) {
+			StackFrame* frame = tls->frames [0];
```
Comment (lambdageek) [inline mono/mini/debugger-agent.c]: I think the behavior we want is:
* if the GC Finalizer thread is idle, don't show it in the thread list.
* if the GC Finalizer is running some finalizer code, show it.

I'm not sure that the code here does that.  I think `frames [0]` is the currently executing function, right?  That means if I have a finalizer that calls some native code, we won't show the finalizer in the debugger.

I wonder if it would be better if the finalizer toggled some flag.  We raise two profiler events around the place where we actually run the managed finalizers:
https://github.com/mono/mono/blob/96b1fd837d6caf1be1b657c0726af3b8caae7060/mono/metadata/gc.c#L925-L932

I think the debugger could add callbacks for those two events to toggle some private bit so that it always knows if any managed finalizers are currently running in the finalizer thread.

Comment (thaystg) [reply mono/mini/debugger-agent.c]: Thanks for the suggestion! Done!

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@monojenkins backport 2019-06

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
@monojenkins build Linux i386
