### PR TITLE
Correctly set ReflectionType with inherited generic methods

### LINKED ISSUE #15070: [netcore] Make System.Reflection.Tests.MemberInfoTests.GenericMethodsInheritTheReflectedTypeOfTheirTemplate Pass
The test currently fails with:

```
System.Reflection.Tests.MemberInfoTests.GenericMethodsInheritTheReflectedTypeOfTheirTemplate [FAIL]
      Assert.Equal() Failure
      Expected: typeof(System.Reflection.Tests.MemberInfoTests+Derived)
      Actual:   typeof(System.Reflection.Tests.MemberInfoTests+Base)
      Stack Trace:
           at System.Reflection.Tests.MemberInfoTests.GenericMethodsInheritTheReflectedTypeOfTheirTemplate()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Determine why and make the test pass.

### PR DESCRIPTION
**Pull request by CoffeeFlux**
Fixes #15070

### CODE REVIEW

File: mono/metadata/reflection.c [hunk 1]
```diff
@@ -2641,6 +2641,10 @@ ves_icall_RuntimeMethodInfo_MakeGenericMethod_impl (MonoReflectionMethodHandle r
 	MonoMethod *imethod = reflection_bind_generic_method_parameters (method, types, error);
 	return_val_if_nok (error, MONO_HANDLE_CAST (MonoReflectionMethod, NULL_HANDLE));
 
+	MonoReflectionType *reftype = MONO_HANDLE_GETVAL (rmethod, reftype);
+	g_assert (reftype->type->type == MONO_TYPE_CLASS);
```
Comment (CoffeeFlux) [inline mono/metadata/reflection.c]: Is this enough for handling the typed union? Is there a scenario where this could be any other type?

Comment (CoffeeFlux) [reply mono/metadata/reflection.c]: Judging by the test suite barking at me, the answer is yes
