### PR TITLE
Fixes #9277

### LINKED ISSUE #9277: Cannot get the exit code from a non-child process on Unix (on Windows)
## Steps to Reproduce

1. Start a process
2. Not sure if UseShellExecute and redirected outputs matter
3. Kill this process
4. Get exit code of the process

### Current Behavior

System.InvalidOperationException is being thrown:

```bash
System.InvalidOperationException: Cannot get the exit code from a non-child process on Unix
  at System.Diagnostics.Process.get_ExitCode () [0x00011] in <ea76b420f6684644b46574e5fa70c83b>:0 
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.get_ExitCode()
  at SimplePM_Server.SimplePM_Tester.ProgramTester.GenerateTestResult () [0x0004d] in <99ae1a52003747f0a7a1ebdcca68627d>:0 
  at SimplePM_Server.SimplePM_Tester.ProgramTester.RunTesting () [0x000aa] in <99ae1a52003747f0a7a1ebdcca68627d>:0 
  at SimplePM_Server.SimplePM_Tester.SimplePM_Tester.Release (System.Object& compilerConfiguration, CompilerBase.ICompilerPlugin& compilerPlugin) [0x00074] in <99ae1a52003747f0a7a1ebdcca68627d>:0 
  at SimplePM_Server.SimplePM_Waiter.RunTesting (CompilerBase.CompilerResult cResult, System.Object& compilerConfiguration, CompilerBase.ICompilerPlugin& compilerPlugin) [0x000d3] in <99ae1a52003747f0a7a1ebdcca68627d>:0 
```

When running application with Microsoft .NET framework all works great, exit code `-1`.

### Expected Behavior

Actual exit code of that process.

## On which platforms did you notice this
**OS**: Microsoft Windows Server 2016 x64
**Version Used**: 5.12.0, 5.14.0.141 x64

### PR DESCRIPTION
**Pull request by sirkadirov**
Unix-only exception is being thrown on Windows, more info in #9277 

Detecting unix platform as recommended on mono website: http://www.mono-project.com/docs/faq/technical/#how-to-detect-the-execution-platform

### CODE REVIEW

File: mcs/class/referencesource/System/services/monitoring/system/diagnosticts/Process.cs [hunk 1]
```diff
@@ -230,7 +230,10 @@ private enum StreamReadMode
             get {
                 EnsureState(State.Exited);
 #if MONO
-                if (exitCode == -1)
+		
+		int platform = (int)Environment.OSVersion.Platform;
+		
+                if (( (platform == 4) || (platform == 6) || (platform == 128) ) && exitCode == -1)
```
Comment (jaykrell) [inline mcs/class/referencesource/System/services/monitoring/system/diagnosticts/Process.cs]: Can we copy the OnUnix or whatever function from somewhere?

Comment (sirkadirov) [reply mcs/class/referencesource/System/services/monitoring/system/diagnosticts/Process.cs]: Yes, ofcource, I'll do it later. And I'm thinking about full deletion of this part of code because many programs use exit code -1...

P.S. Sorry for bad English!

Comment (marek-safar) [reply mcs/class/referencesource/System/services/monitoring/system/diagnosticts/Process.cs]: Just do `if (exitCode == -1 && !RuntimeInformation.IsOSPlatform (OSPlatform.Windows))`

**Comment by marek-safar** [comment]
approve

**Comment by akoeplinger** [comment]
@monojenkins backport 2018-06

**Comment by akoeplinger** [comment]
@sirkadirov Thank you for the contribution!
