### PR TITLE
Remove/Update deprecated TZs for #16415

### LINKED ISSUE #16415: Timezone data not handled correctly on FreeBSD
## Steps to Reproduce

This problem is reliably reproduced by the FreeBSD-12 community CI runs.
Failures are observed in the `corlib` test lane. It is expected a test program would confirm this affects operation, but I do not have a test program available.

### Current Behavior

```
4) ConvertTime_AjustmentConvertTimeWithSourceTimeZone (MonoTests.System.TimeZoneInfoTest+ConvertTimeTests.ConvertTime_AjustmentConvertTimeWithSourceTimeZone)
   System.TimeZoneNotFoundException : The time zone ID 'US/Eastern' was not found on the local computer.
  ----> System.IO.DirectoryNotFoundException : Could not find a part of the path "/usr/share/zoneinfo/US/Eastern".
  at System.TimeZoneInfo.FindSystemTimeZoneById (System.String id) [0x00096] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/external/corefx/src/Common/src/CoreLib/System/TimeZoneInfo.Unix.cs:726 
  at MonoTests.System.TimeZoneInfoTest+ConvertTimeTests.ConvertTime_AjustmentConvertTimeWithSourceTimeZone () [0x00000] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/mcs/class/corlib/Test/System/TimeZoneInfoTest.cs:747 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:395 
--DirectoryNotFoundException
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0015e] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/mcs/class/corlib/System.IO/FileStream.cs:223 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize) [0x00000] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/mcs/class/corlib/System.IO/FileStream.cs:96 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int)
  at System.IO.File.ReadAllBytes (System.String path) [0x00000] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/external/corefx/src/System.IO.FileSystem/src/System/IO/File.cs:338 
  at System.TimeZoneInfo.TryGetTimeZoneFromLocalMachine (System.String id, System.TimeZoneInfo& value, System.Exception& e) [0x00012] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/external/corefx/src/Common/src/CoreLib/System/TimeZoneInfo.Unix.cs:213 
```

### Expected Behavior

The expected behavior is for the tests to pass except for those tests which do not have a corresponding entry in `/usr/share/zoneinfo/zone.tab`. This is reflected in the corlib tests. The significant differences in TZ databases means a closer look at how these tests are performed, and could obviously cause significant problems in operation.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows
[X] FreeBSD

**Version Used**: master

## Stacktrace

```
4) ConvertTime_AjustmentConvertTimeWithSourceTimeZone (MonoTests.System.TimeZoneInfoTest+ConvertTimeTests.ConvertTime_AjustmentConvertTimeWithSourceTimeZone)
   System.TimeZoneNotFoundException : The time zone ID 'US/Eastern' was not found on the local computer.
  ----> System.IO.DirectoryNotFoundException : Could not find a part of the path "/usr/share/zoneinfo/US/Eastern".
  at System.TimeZoneInfo.FindSystemTimeZoneById (System.String id) [0x00096] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/external/corefx/src/Common/src/CoreLib/System/TimeZoneInfo.Unix.cs:726 
  at MonoTests.System.TimeZoneInfoTest+ConvertTimeTests.ConvertTime_AjustmentConvertTimeWithSourceTimeZone () [0x00000] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/mcs/class/corlib/Test/System/TimeZoneInfoTest.cs:747 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:395 
--DirectoryNotFoundException
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0015e] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/mcs/class/corlib/System.IO/FileStream.cs:223 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize) [0x00000] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/mcs/class/corlib/System.IO/FileStream.cs:96 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int)
  at System.IO.File.ReadAllBytes (System.String path) [0x00000] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/external/corefx/src/System.IO.FileSystem/src/System/IO/File.cs:338 
  at System.TimeZoneInfo.TryGetTimeZoneFromLocalMachine (System.String id, System.TimeZoneInfo& value, System.Exception& e) [0x00012] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/external/corefx/src/Common/src/CoreLib/System/TimeZoneInfo.Unix.cs:213 


5) ConvertTimeTests.ConvertTime_AjustmentConvertTimeWithSourceTimeZone (MonoTests.System.TimeZoneInfoTest+ConvertTimeTests_LocalUtc.ConvertTimeTests.ConvertTime_AjustmentConvertTimeWithSourceTimeZone)
   System.TimeZoneNotFoundException : The time zone ID 'US/Eastern' was not found on the local computer.
  ----> System.IO.DirectoryNotFoundException : Could not find a part of the path "/usr/share/zoneinfo/US/Eastern".
  at System.TimeZoneInfo.FindSystemTimeZoneById (System.String id) [0x00096] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/external/corefx/src/Common/src/CoreLib/System/TimeZoneInfo.Unix.cs:726 
  at MonoTests.System.TimeZoneInfoTest+ConvertTimeTests.ConvertTime_AjustmentConvertTimeWithSourceTimeZone () [0x00000] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/mcs/class/corlib/Test/System/TimeZoneInfoTest.cs:747 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:395 
--DirectoryNotFoundException
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0015e] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/mcs/class/corlib/System.IO/FileStream.cs:223 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize) [0x00000] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/mcs/class/corlib/System.IO/FileStream.cs:96 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int)
  at System.IO.File.ReadAllBytes (System.String path) [0x00000] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/external/corefx/src/System.IO.FileSystem/src/System/IO/File.cs:338 
  at System.TimeZoneInfo.TryGetTimeZoneFromLocalMachine (System.String id, System.TimeZoneInfo& value, System.Exception& e) [0x00012] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/external/corefx/src/Common/src/CoreLib/System/TimeZoneInfo.Unix.cs:213 


6) SubminuteDSTOffsets (MonoTests.System.TimeZoneInfoTest+FindSystemTimeZoneByIdTests.SubminuteDSTOffsets)
   System.TimeZoneNotFoundException : The time zone ID 'Canada/Newfoundland' was not found on the local computer.
  ----> System.IO.DirectoryNotFoundException : Could not find a part of the path "/usr/share/zoneinfo/Canada/Newfoundland".
  at System.TimeZoneInfo.FindSystemTimeZoneById (System.String id) [0x00096] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/external/corefx/src/Common/src/CoreLib/System/TimeZoneInfo.Unix.cs:726 
  at MonoTests.System.TimeZoneInfoTest+FindSystemTimeZoneByIdTests.SubminuteDSTOffsets () [0x00050] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/mcs/class/corlib/Test/System/TimeZoneInfoTest.cs:1030 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:395 
--DirectoryNotFoundException
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0015e] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/mcs/class/corlib/System.IO/FileStream.cs:223 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize) [0x00000] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/mcs/class/corlib/System.IO/FileStream.cs:96 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int)
  at System.IO.File.ReadAllBytes (System.String path) [0x00000] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/external/corefx/src/System.IO.FileSystem/src/System/IO/File.cs:338 
  at System.TimeZoneInfo.TryGetTimeZoneFromLocalMachine (System.String id, System.TimeZoneInfo& value, System.Exception& e) [0x00012] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/external/corefx/src/Common/src/CoreLib/System/TimeZoneInfo.Unix.cs:213 


7) Bug_9664 (MonoTests.System.TimeZoneInfoTest+IsDaylightSavingTimeTests.Bug_9664)
   System.TimeZoneNotFoundException : The time zone ID 'US/Central' was not found on the local computer.
  ----> System.IO.DirectoryNotFoundException : Could not find a part of the path "/usr/share/zoneinfo/US/Central".
  at System.TimeZoneInfo.FindSystemTimeZoneById (System.String id) [0x00096] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/external/corefx/src/Common/src/CoreLib/System/TimeZoneInfo.Unix.cs:726 
  at MonoTests.System.TimeZoneInfoTest+IsDaylightSavingTimeTests.Bug_9664 () [0x00000] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/mcs/class/corlib/Test/System/TimeZoneInfoTest.cs:447 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:395 
--DirectoryNotFoundException
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0015e] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/mcs/class/corlib/System.IO/FileStream.cs:223 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize) [0x00000] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/mcs/class/corlib/System.IO/FileStream.cs:96 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int)
  at System.IO.File.ReadAllBytes (System.String path) [0x00000] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/external/corefx/src/System.IO.FileSystem/src/System/IO/File.cs:338 
  at System.TimeZoneInfo.TryGetTimeZoneFromLocalMachine (System.String id, System.TimeZoneInfo& value, System.Exception& e) [0x00012] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/external/corefx/src/Common/src/CoreLib/System/TimeZoneInfo.Unix.cs:213 


8) FindSystemTimeZoneById (MonoTests.System.TimeZoneTest.FindSystemTimeZoneById)
   System.TimeZoneNotFoundException : The time zone ID 'Canada/Eastern' was not found on the local computer.
  ----> System.IO.DirectoryNotFoundException : Could not find a part of the path "/usr/share/zoneinfo/Canada/Eastern".
  at System.TimeZoneInfo.FindSystemTimeZoneById (System.String id) [0x00096] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/external/corefx/src/Common/src/CoreLib/System/TimeZoneInfo.Unix.cs:726 
  at MonoTests.System.TimeZoneTest.FindSystemTimeZoneById () [0x00000] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/mcs/class/corlib/Test/System/TimeZoneTest.cs:367 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:395 
--DirectoryNotFoundException
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0015e] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/mcs/class/corlib/System.IO/FileStream.cs:223 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize) [0x00000] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/mcs/class/corlib/System.IO/FileStream.cs:96 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int)
  at System.IO.File.ReadAllBytes (System.String path) [0x00000] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/external/corefx/src/System.IO.FileSystem/src/System/IO/File.cs:338 
  at System.TimeZoneInfo.TryGetTimeZoneFromLocalMachine (System.String id, System.TimeZoneInfo& value, System.Exception& e) [0x00012] in /mnt/jenkins/workspace/test-mono-mainline-community/label/freebsd-12-amd64/external/corefx/src/Common/src/CoreLib/System/TimeZoneInfo.Unix.cs:213 
```

### PR DESCRIPTION
**Pull request by rootwyrm**
This fixes #16415 

All timezones indicated as deprecated have been updated to the current IANA specification.

### CODE REVIEW

File: mcs/class/corlib/Test/System/TimeZoneInfoTest.cs [hunk 1]
```diff
@@ -54,11 +54,11 @@ public static string MapTimeZoneId (string id)
 					return "New Zealand Standard Time";
 				case "Europe/Athens":
 					return "GTB Standard Time";
-				case "US/Eastern":
+				case "America/New_York":
 					return "Eastern Standard Time";
-				case "US/Central":
+				case "America/Chicago":
```
Comment (akoeplinger) [inline mcs/class/corlib/Test/System/TimeZoneInfoTest.cs]: There's still a usage of `US/Central` in the `Bug_9664` test.

Comment (akoeplinger) [reply mcs/class/corlib/Test/System/TimeZoneInfoTest.cs]: OK, I'm fine if you revert this here and add logic to skip Bug_9664() if US/Central can't be found, e.g. like this:

```diff
			[Test]
			public void Bug_9664 ()
			{
-				TimeZoneInfo tzi = TimeZoneInfo.FindSystemTimeZoneById (MapTimeZoneId ("US/Central"));
+				TimeZoneInfo tzi;
+				try {
+					tzi = TimeZoneInfo.FindSystemTimeZoneById (MapTimeZoneId ("US/Central"));
+				} catch (TimeZoneNotFoundException e) {
+					Assert.Ignore ("Timezone US/Central not found.");
+				}
```

Comment (akoeplinger) [inline mcs/class/corlib/Test/System/TimeZoneInfoTest.cs]: we need to keep the `"US/Central"` case here since it is still used by `Bug_9664 ()` now.

File: mcs/class/corlib/Test/System/TimeZoneInfoTest.cs [hunk 2]
```diff
@@ -70,7 +70,7 @@ public static string MapTimeZoneId (string id)
 				case "Europe/Rome":
 				case "Europe/Vatican":
 					return "W. Europe Standard Time";
-				case "Canada/Eastern":
+				case "America/Toronto":
```
Comment (akoeplinger) [inline mcs/class/corlib/Test/System/TimeZoneInfoTest.cs]: `TimeZoneTest.FindSystemTimeZoneById()` needs to be changed to `America/Toronto` too.

**Comment by akoeplinger** [comment]
@monojenkins whitelist
