### PR TITLE
[runtime] Disallow casts between int[] and IList<int?> etc.

### LINKED ISSUE #6401: Invalid array cast is supported
## Steps to Reproduce

Compile & Run
```csharp
using System.Collections.Generic;

class Program {
	static void Main (string [] args)
	{
		object intArray = new[] { 1, 2, 3 };
		IList<int?> oo = (IList<int?>)intArray;
	}
}
```

## Current Behavior

No invalid cast exception

## Expected Behavior

```System.InvalidCastException: Unable to cast object of type 'System.Int32[]' to type 'System.Collections.Generic.IList`1[System.Nullable`1[System.Int32]]'.```

### On which platforms did you notice this

[x ] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 5.11.0 (master/1b249d561e8 Tue Jan  2 14:16:34 CET 2018)

### PR DESCRIPTION
**Pull request by vargaz**
Fixes #6401

### CODE REVIEW

**Comment by Therzok** [comment]
Does:
```
public static void Main() {
        object arr = new int? [10];
        if (arr is IList<int?>) {
            Console.WriteLine("xyz");
        }
    }
```

Still work? .NET seems to suggest it should: https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOwD4AEAMABLgIwDcAsAFAHEkAslV1uAzMQEyEDChA3tUJDi7UgDZi9OgA4AFAEp+g4SoD2wAFZwAxjEIQECQgF5CmOAHdCAS0wwA/IQDaJfAF0mKldYBmhWQZG1lCEAJIAMsEwADy2DgB8igJUXql0AJyyAEQAHgCeAF5Z8p5pAL7KQhVUZUA

**Comment by marek-safar** [comment]
build

File: mono/metadata/class.c [hunk 1]
```diff
@@ -8411,13 +8411,15 @@ mono_class_is_assignable_from (MonoClass *klass, MonoClass *oklass)
 
 			// If the target we're trying to cast to is a valuetype, we must account of weird valuetype equivalences such as IntEnum <> int or uint <> int
 			// We can't apply it for ref types as this would go wrong with arrays - IList<byte[]> would have byte tested
-			if (iface_klass->valuetype)
```
Comment (lewurm) [inline mono/metadata/class.c]: that comment above should be moved into the `if` block imho

**Comment by marek-safar** [comment]
Please backport to 2017-12

**Comment by luhenry** [comment]
@monojenkins build Linux AArch64

**Comment by luhenry** [comment]
@monojenkins build Linux AArch64 Interpreter

**Comment by luhenry** [comment]
@monojenkins build Linux i386

**Comment by luhenry** [comment]
@monojenkins build Linux x64 FullAOT

**Comment by luhenry** [comment]
@monojenkins build Linux ARMv7 hard float interpreter
