### PR TITLE
Plug leak of CustomAttribute initializer name

### LINKED ISSUE #14543: Decoded custom attribute values leak the encoded value receiver
## Steps to Reproduce

1. See attached source and leaks report: https://gist.github.com/Therzok/d2e8322a9f1cd4608981dbd43ccfd83b
2. run `MallocStackLogging=YES mono --debug a.exe`
3. `leaks mono`

### Current Behavior

Unbounded leak of CustomAttribute field/property initializer name. Leaks were of type: FieldName, PropName, FieldType. Haven't seen PropType.

### Expected Behavior

No leak of attribute receiver name.

## On which platforms did you notice this

[*] macOS
[ ] Linux
[ ] Windows

**Version Used**:
Mono JIT compiler version 5.18.1.26 (pull-request-14392/d76505c27ee Wed May  8 08:28:00 EDT 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	Interpreter:   yes
	LLVM:          yes(600)
	Suspend:       preemptive
	GC:            sgen (concurrent by default)## Stacktrace

```
Please paste the stack trace here if available.
```

### PR DESCRIPTION
**Pull request by Therzok**
All the CustomAttribute initializer names (fields, property) except the last were leaked. Ensure all names are freed.

Fixes #14543

### CODE REVIEW

File: mono/metadata/custom-attrs.c [hunk 1]
```diff
@@ -980,15 +980,17 @@ create_custom_attr (MonoImage *image, MonoMethod *method, const guchar *data, gu
 			mono_property_set_value_handle (prop, attr, pparams, error);
 			goto_if_nok (error, fail);
 		}
+		
+		g_free (name);
```
Comment (baulig) [inline mono/metadata/custom-attrs.c]: Shouldn't we NULL-out the value after it's been freed?

```suggestion
		g_free (name);
		name = NULL;
```

File: mono/metadata/custom-attrs.c [hunk 2]
```diff
@@ -980,15 +980,17 @@ create_custom_attr (MonoImage *image, MonoMethod *method, const guchar *data, gu
...
 	}
 
 	goto exit;
 fail:
+	g_free (name);
```
Comment (baulig) [inline mono/metadata/custom-attrs.c]:
```suggestion
	g_free (name);
	name = NULL;
```

**Comment by lambdageek** [comment]
@monojenkins build failed

(unrelated flaky tests)

**Comment by Therzok** [comment]
@monojenkins backport 2019-02

**Comment by marek-safar** [comment]
@monojenkins backport 2019-04
