### PR TITLE
Remove MAX_PATH usage in w32process

### LINKED ISSUE #14730: Assertion at /Users/builder/jenkins/workspace/archive-mono/2019-02/mac/release/mono/utils/strenc.c:184, condition `utf8!=NULL' not met
## Steps to Reproduce

Unfortunately I don't have a way to reproduce this, it's a random issue and it's hit twice today, with two different Xamarin.Mac tests.

Reference: https://github.com/xamarin/maccore/issues/1685

I have the crash info dumped to the terminal:

* https://gist.github.com/rolfbjarne/9c294a19c1a0fc9fd4883263a5cae1d3
* https://gist.github.com/rolfbjarne/56220c52d47db8bde35dfedbfc717386

and the native stack trace looks identical in both:

```
0x11001f3cf - test.app/Contents/MacOS/test : monoeg_assertion_message
0x110017dbe - test.app/Contents/MacOS/test : mono_unicode_to_external
0x1100090bf - test.app/Contents/MacOS/test : mono_pe_file_map
0x10ffa5bb1 - test.app/Contents/MacOS/test : mono_w32process_get_fileversion_info
0x10ffa7cc1 - test.app/Contents/MacOS/test : mono_w32process_get_fileversion
0x10ffa8a6b - test.app/Contents/MacOS/test : ves_icall_System_Diagnostics_Process_GetModules_internal
```

This is with xamarin-macios [from today](https://github.com/xamarin/xamarin-macios/commit/8e2bbe8d2dc8ddb74106504981ae58970a0263b1
); mono hash is bab25c0a80f7a9ad8f1f18be227119384e3ec0a0 (2019-02).

### PR DESCRIPTION
**Pull request by CoffeeFlux**
Fixes #14730

Not totally sure my Windows code is correct here, so it's a draft until I can look at CI results.

### CODE REVIEW

**Comment by jaykrell** [comment]
```
gboolean
mono_get_module_filename (HMODULE mode, gunichar2** pstr, guint32* plength)
{
  gunichar* str= = NULL;
  guint32 capacity = 64;
  guint32 length = 0;
  gboolean success = FALSE;

  while (true)
  {
     length = 0;
     str = g_new (gunichar2, capacity);
     if (!str)
        break;
     length = GetModuleFileName (mod, str, capacity);
     success = length && length < capacity;
     if (success)
        break;
     g_free(str); // error or too small
     str = NULL; 
     capacity *= 2;
     if (!length) // error 
        break;
  }
  *pstr = str;
  *plength = length;
  return success;
}
```
?

One call to each function.
One write through each out parameter.
One exit path.
This function can be slow, but it should also contribute minimal size to the overall runtime.

**Comment by CoffeeFlux** [comment]
Oh also, @rolfbjarne how far will you need this backported?

**Comment by CoffeeFlux** [comment]
@monojenkins build failed

**Comment by CoffeeFlux** [comment]
@monojenkins build failed

File: mono/metadata/w32process.c [hunk 1]
```diff
@@ -561,9 +595,9 @@ ves_icall_System_Diagnostics_Process_GetModules_internal (MonoObjectHandle this_
 	return_val_if_nok (error, NULL_HANDLE_ARRAY);
 
 	for (i = 0; i < module_count; i++) {
-		if (mono_w32process_module_get_name (process, mods [i], modname, MAX_PATH)
-			 && mono_w32process_module_get_filename (process, mods [i], filename, MAX_PATH))
-		{
+		modname = mono_w32process_module_get_name (process, mods [i], &modname_len);
+		filename = mono_w32process_module_get_filename (process, mods [i], &filename_len);
+		if (modname && filename) {
```
Comment (jaykrell) [inline mono/metadata/w32process.c]: If modname is null, should you call get_filename?

File: mono/metadata/w32process.c [hunk 2]
```diff
@@ -561,13 +595,19 @@ ves_icall_System_Diagnostics_Process_GetModules_internal (MonoObjectHandle this_
...
-			return_val_if_nok (error, NULL_HANDLE_ARRAY);
+			if (!is_ok (error)) {
+				g_free (modname);
+				g_free (filename);
+				return NULL_HANDLE_ARRAY;
+			}
 			MONO_HANDLE_ARRAY_SETREF (temp_arr, num_added++, module);
 		}
+		g_free (modname);
+		g_free (filename);
```
Comment (jaykrell) [inline mono/metadata/w32process.c]: You don't need to free twice.
Instead:
```
  if (!is_ok (error))
    break;
  array setref
 }
g_free twice
if (!is_ok())
  return
```

File: mono/metadata/w32process-unix.c [hunk 3]
```diff
@@ -911,82 +911,64 @@ mono_w32process_try_get_modules (gpointer handle, gpointer *modules, guint32 siz
...
+		return NULL;
 
 	proc_path = mono_unicode_from_external (path, &bytes);
-	g_free (path);
-
-	if (proc_path == NULL)
-		return 0;
 
-	len = (bytes / 2);
+	*len = bytes / sizeof (gunichar2);
```
Comment (jaykrell) [inline mono/metadata/w32process-unix.c]: Aside: Windows code used to always `<< 1` and `>> 1` but that fell out of fashion.

**Comment by rolfbjarne** [comment]
@CoffeeFlux back porting back to 2019-08 would be nice.

File: mono/metadata/w32process.c (hunk 1 above)
Comment (CoffeeFlux) [reply mono/metadata/w32process.c]: I don't think it makes much of a difference, given that's not a common scenario.

File: mono/metadata/w32process.c (hunk 2 above)
Comment (CoffeeFlux) [reply mono/metadata/w32process.c]: I don't think the code you suggested will work since they have to be freed each iteration of the loop, but you're right that this can be cleaned up a bit to only free once.

Comment (jaykrell) [reply mono/metadata/w32process.c]: The old code stopped at the first error and returned.
So either undo this part, sorry, or try for single point of exit.

Comment (CoffeeFlux) [reply mono/metadata/w32process.c]: Check my latest commit and see if you think that's fine, I tried to clean it up.

**Comment by CoffeeFlux** [comment]
@monojenkins build failed

**Comment by CoffeeFlux** [comment]
@monojenkins build failed

**Comment by CoffeeFlux** [comment]
@monojenkins build failed

**Comment by CoffeeFlux** [comment]
@monojenkins backport to 2019-08

File: mono/metadata/w32process.c (hunk 2 above)
Comment (jaykrell) [reply mono/metadata/w32process.c]: I don’t think so but hard to see in github on phone. The old code stopped the loop upon error. This does not seem to.

Comment (jaykrell) [reply mono/metadata/w32process.c]: Oh oops probably. Just hard to see indent on phone.

**Comment by jaykrell** [comment]
I suggest you take helper function(s) from other PR. Backport should not be a problem.
