### PR TITLE
Fix deadlock on Alpine

### LINKED ISSUE #7167: Alpine Linux build is broken
## Steps to Reproduce

1. Run build on Alpine Linux
2. The build runs very slowly during the `make` step (~4 hrs instead of 35mins) and then runs into all the timeouts of test steps so it's essentially broken

This started with https://jenkins.mono-project.com/job/test-mono-mainline-docker/label=docker-alpine/573/ which makes these commits suspect:

~1.  \[System\] System.Net.* tests from corefx (+RemoteExecutorTestBase) ([commit](https://github.com/mono/mono/commit/e9e17e069e6949600a382341e8888d7486553f21))~
~2.  IOS SDKs (# 6257) ([commit](https://github.com/mono/mono/commit/a2407ac76a50cc1b5fdfbea83adb135d9be40356))~
~3.  Remove a few braces that are contrary to our prescribed style. (# 6245) ([commit](https://github.com/mono/mono/commit/891941ecbe9640b180f73096b8b230c6f48bf11b))~
~4.  \[threads\] Ensure we remove the thread only once (# 6194) ([commit](https://github.com/mono/mono/commit/f6bf1d427b29ba00211f047081e492c56d06b41c))~
5.  \[threadpool\] Replace parked_threads condition variable by a semaphore ([commit](https://github.com/mono/mono/commit/5f5c5e97a08f7086d7c18af37352c4a03dc4c0d1))
~6.  \[runtime\] Fixes issue when compiling with -no\_weak\_imports (# 6276) ([commit](https://github.com/mono/mono/commit/6ca7b346cd3fc52318caccc182f35b8425439a07))~
~7.  Minor cleanup split out and expanded from another larger change. (# 6263) ([commit](https://github.com/mono/mono/commit/fba6bfc9549fb8686576cca20e33df4d01fb2d1a))~
~8.  This list is almost sorted -- so repair the sorting and add comment. ([commit](https://github.com/mono/mono/commit/11e18c2a5d6ed7d17184ad4d5e0606ab1e7ec334))~
~9.  Only call \`waitpid\` for processes that Mono tracks, rather than all ([commit](https://github.com/mono/mono/commit/8c9c37c45bb3302f917fe345004a5076c21d5ba1))~
~10.  cooperative suspend babystep wrt ([commit](https://github.com/mono/mono/commit/e0b1d6651915c395eca637ed172399354ee0fa17))~
~11.  \[System.Windows.Forms\] Fix CJK Encoding on Window Title ([commit](https://github.com/mono/mono/commit/c0e6ecb6c2ced241811e5569bfd483acd9cf6d94))~
~12.  \[mono-api-html\] do not warn about removal of \[Obsolete\] member. (#5294) ([commit](https://github.com/mono/mono/commit/05d5204da8f26549cf2e8ae387d907f6a4748823))~
~13.  \[System.Core\] Use corefx System.Linq tests (25k tests) (# 5515) ([commit](https://github.com/mono/mono/commit/cae8dd6dbd9253c0abbe2ab0a000ac617f116a78))~

I've crossed out those which I think are unrelated.

_Edit:_ **https://github.com/mono/mono/issues/7167#issuecomment-375898239 confirms 5f5c5e97 to be the issue**

## Current Behavior

Build is so slow that it is essentially broken.

## Expected Behavior

Not broken.

### On which platforms did you notice this

[ ] macOS
[ X ] Linux (Alpine)
[ ] Windows

**Version Used**: master

### PR DESCRIPTION
**Pull request by rickardp**
Fixes #7167

The PR 3e8108ea6576b07de2a64528be18674683879189 introduced a deadlock on Alpine, making it impossible to even build mono. This PR reverts the setting of PTHREAD_PRIO_INHERIT when on Alpine.
Since GCC on Alpine doesn't provide a builtin macro to detect Alpine, I also added a #define in configure.ac.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/mono/mono?pullRequest=19914) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/mono/mono?pullRequest=19914) before we can accept your contribution.<br/><br/>:x: rickardp [sign now](https://cla.dotnetfoundation.org/mono/mono?pullRequest=19914)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/mono/mono?pullRequest=19914) it.</sub>

File: mono/utils/mono-os-mutex.h [hunk 1]
```diff
@@ -59,7 +59,7 @@ mono_os_mutex_init_type (mono_mutex_t *mutex, int type)
 	if (G_UNLIKELY (res != 0))
 		g_error ("%s: pthread_mutexattr_settype failed with \"%s\" (%d)", __func__, g_strerror (res), res);
 
-#if !defined(__HAIKU__) && defined (PTHREAD_PRIO_INHERIT) && HAVE_DECL_PTHREAD_MUTEXATTR_SETPROTOCOL
+#if !defined(__HAIKU__) && !defined(MUSL) && defined (PTHREAD_PRIO_INHERIT) && HAVE_DECL_PTHREAD_MUTEXATTR_SETPROTOCOL
 	/* use PTHREAD_PRIO_INHERIT if possible */
```
Comment (Cogitri) [inline mono/utils/mono-os-mutex.h:63]: Usually instead of testing for musl testing for glibc is done, so maybe `&& defined(__GLIBC)` does the trick?

Comment (jaykrell) [reply mono/utils/mono-os-mutex.h:63]: That asssumes other libc has the same bug as muslc.
It is a bug in muslc, right?

Comment (Cogitri) [reply mono/utils/mono-os-mutex.h:63]: Not sure about that, I just think that detecting this via the triplet might be a bit fragile. I suppose the musl folks would know more, maybe you could contact them in #musl on freenode. Anyway, thanks for looking into this :)

Comment (rickardp) [reply mono/utils/mono-os-mutex.h:63]: > `defined(__GLIBC__)`

I considered that first, but I took a more conservative approach since I have no way of testing other libc implementations - I only know this fixes the issue on muslc.

I am not sure about other OSes that potentially uses pthread but not glibc? I can only find the cases Pthread, Win32 and no threads. I wouldn't know if my fix breaks on e.g. Solaris.

That said, I am happy to change it if there is a better solution.

Comment (rootwyrm) [reply mono/utils/mono-os-mutex.h:63]: We should prefer the `!defined(MUSL)` fix here because multiple OSes may hit `defined(__GLIBC__)` even when unintended. This isn't necessarily a bug as much as a difference in how pthreads and timers behave on different implementations. FreeBSD exhibits basically identical behavior, just doesn't go fully broken.

We should probably also add a 'todo' to make autoconf more `musl`-aware as a whole than it is currently.

**Comment by akoeplinger** [comment]
@monojenkins build

File: mono/utils/mono-os-mutex.h (hunk 1 above)
Comment (Cogitri) [reply mono/utils/mono-os-mutex.h:63]: Ah okie :+1:
