### PR TITLE
Set inited flag _after_ TermInfoDriver initialisation completes

### LINKED ISSUE #18317: DivideByZeroException with concurrent initialisation of TermInfoDriver
## Steps to Reproduce

1. Create an empty .net console app targeting net461
2. Attempt to access any of the lockable properties from TermInfoDriver on multiple threads (example property I'm using is Background/ForegroundColor: https://github.com/mono/mono/blob/cf24b9f9d4b80512122f998a47cae850df1d4cb2/mcs/class/corlib/System/TermInfoDriver.cs#L403-L435)

#### Sample code to show exception
```
class Program
    {
		public static void Main(string[] args)
		{
			Parallel.Invoke(
				() => { var x = Console.ForegroundColor; },
				() => { Console.BackgroundColor = ConsoleColor.Black; }
			);
		}
    }
```

3. Build and run the application

### Current Behavior

Occasionally, the application will run without an issue.  However, most of the time an exception is thrown due to the behaviour I've described in this other thread [here](https://github.com/akkadotnet/akka.net/issues/2432#issuecomment-568130295).

### Expected Behavior

No exception should be thrown.

## On which platforms did you notice this

[x] macOS
[x] Linux
[x] Windows

**Version Used**:

6.4.0

## Stacktrace

```
Unhandled Exception:
System.AggregateException: One or more errors occurred. ---> System.DivideByZeroException: Attempted to divide by zero.
  at System.TermInfoDriver.ChangeColor (System.String format, System.ConsoleColor color) [0x00016] in <filename unknown>:0 
  at System.TermInfoDriver.set_BackgroundColor (System.ConsoleColor value) [0x00011] in <filename unknown>:0 
  at System.ConsoleDriver.set_BackgroundColor (System.ConsoleColor value) [0x0001f] in <filename unknown>:0 
  at System.Console.set_BackgroundColor (System.ConsoleColor value) [0x00000] in <filename unknown>:0 
  at akka_test.Program+<>c.<Main>b__0_1 () [0x00001] in <filename unknown>:0 
  at System.Threading.Tasks.Task.InnerInvoke () [0x00012] in <filename unknown>:0 
  at System.Threading.Tasks.Task.Execute () [0x00016] in <filename unknown>:0 
[MVID] 2320d006b1a64388aa1812d52f51bde3 4
[MVID] 7747cf446af449e194e4b4e70d85e773 0,1,2,3,5,6
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.FastWaitAll (System.Threading.Tasks.Task[] tasks) [0x0006e] in <filename unknown>:0 
  at System.Threading.Tasks.Parallel.Invoke (System.Threading.Tasks.ParallelOptions parallelOptions, System.Action[] actions) [0x0032e] in <filename unknown>:0 
[MVID] 7747cf446af449e194e4b4e70d85e773 0,1
---> (Inner Exception #0) System.DivideByZeroException: Attempted to divide by zero.
  at System.TermInfoDriver.ChangeColor (System.String format, System.ConsoleColor color) [0x00016] in <filename unknown>:0 
  at System.TermInfoDriver.set_BackgroundColor (System.ConsoleColor value) [0x00011] in <filename unknown>:0 
  at System.ConsoleDriver.set_BackgroundColor (System.ConsoleColor value) [0x0001f] in <filename unknown>:0 
  at System.Console.set_BackgroundColor (System.ConsoleColor value) [0x00000] in <filename unknown>:0 
  at akka_test.Program+<>c.<Main>b__0_1 () [0x00001] in <filename unknown>:0 
  at System.Threading.Tasks.Task.InnerInvoke () [0x00012] in <filename unknown>:0 
  at System.Threading.Tasks.Task.Execute () [0x00016] in <filename unknown>:0 
[MVID] 2320d006b1a64388aa1812d52f51bde3 4
[MVID] 7747cf446af449e194e4b4e70d85e773 0,1,2,3,5,6<---

[ERROR] FATAL UNHANDLED EXCEPTION: System.AggregateException: One or more errors occurred. ---> System.DivideByZeroException: Attempted to divide by zero.
  at System.TermInfoDriver.ChangeColor (System.String format, System.ConsoleColor color) [0x00016] in <filename unknown>:0 
  at System.TermInfoDriver.set_BackgroundColor (System.ConsoleColor value) [0x00011] in <filename unknown>:0 
  at System.ConsoleDriver.set_BackgroundColor (System.ConsoleColor value) [0x0001f] in <filename unknown>:0 
  at System.Console.set_BackgroundColor (System.ConsoleColor value) [0x00000] in <filename unknown>:0 
  at akka_test.Program+<>c.<Main>b__0_1 () [0x00001] in <filename unknown>:0 
  at System.Threading.Tasks.Task.InnerInvoke () [0x00012] in <filename unknown>:0 
  at System.Threading.Tasks.Task.Execute () [0x00016] in <filename unknown>:0 
[MVID] 2320d006b1a64388aa1812d52f51bde3 4
[MVID] 7747cf446af449e194e4b4e70d85e773 0,1,2,3,5,6
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.FastWaitAll (System.Threading.Tasks.Task[] tasks) [0x0006e] in <filename unknown>:0 
  at System.Threading.Tasks.Parallel.Invoke (System.Threading.Tasks.ParallelOptions parallelOptions, System.Action[] actions) [0x0032e] in <filename unknown>:0 
[MVID] 7747cf446af449e194e4b4e70d85e773 0,1
---> (Inner Exception #0) System.DivideByZeroException: Attempted to divide by zero.
  at System.TermInfoDriver.ChangeColor (System.String format, System.ConsoleColor color) [0x00016] in <filename unknown>:0 
  at System.TermInfoDriver.set_BackgroundColor (System.ConsoleColor value) [0x00011] in <filename unknown>:0 
  at System.ConsoleDriver.set_BackgroundColor (System.ConsoleColor value) [0x0001f] in <filename unknown>:0 
  at System.Console.set_BackgroundColor (System.ConsoleColor value) [0x00000] in <filename unknown>:0 
  at akka_test.Program+<>c.<Main>b__0_1 () [0x00001] in <filename unknown>:0 
  at System.Threading.Tasks.Task.InnerInvoke () [0x00012] in <filename unknown>:0 
  at System.Threading.Tasks.Task.Execute () [0x00016] in <filename unknown>:0 
[MVID] 2320d006b1a64388aa1812d52f51bde3 4
[MVID] 7747cf446af449e194e4b4e70d85e773 0,1,2,3,5,6<---


Process finished with exit code 1.

```

## Notes

The core problem is that the lock on an uninitialised TermInfoDriver happens immediately upon accessing a property (get or set) and is released immediately before the initialisation process is complete.  So, subsequent calls which happen concurrently will complete before any expected fields are present.

I'm not sure about the best way to fix this but it would be good to have this lock released *after* the initialisation process happens, but we would need to potentially try/catch the whole init block to account for exceptions.

### PR DESCRIPTION
**Pull request by nagytech**
This flag was causing issues when accessing console properties on concurrent threads during TermInfoDriver initialisation.

Fixes #18317

### CODE REVIEW

**Comment by lambdageek** [comment]
approve

File: mcs/class/corlib/System/TermInfoDriver.cs [hunk 1]
```diff
@@ -265,6 +264,8 @@ public void Init ()
 					cursorLeft = 0;
 					cursorTop = 0;
 				}
+
+				inited = true;
```
Comment (lambdageek) [inline mcs/class/corlib/System/TermInfoDriver.cs]: I wonder if this needs to be done in a `try`/`finally` block - otherwise if initialization fails on the first thread, other threads will keep trying.  Not sure whether that's desirable.

/cc @steveisok and team

Comment (steveisok) [reply mcs/class/corlib/System/TermInfoDriver.cs]: I would prefer `try/finally` over this.

Comment (nagytech) [reply mcs/class/corlib/System/TermInfoDriver.cs]: @steveisok I've added `try/finally` as suggested.  Thanks for the feedback.

**Comment by jaykrell** [comment]
Looks racy -- more on-demand initialization, and without data dependency..

**Comment by jaykrell** [comment]
Generic fix is to put all the state behind one pointer, that goes from null to non-null, once.

**Comment by lambdageek** [comment]
@jaykrell how is it racy? it's behind a lock...

**Comment by jaykrell** [comment]
1. Why is try/finally preferred? Do you want retry upon failure, or sticky failure, and is failure well handled either way? Try/finally makes failure sticky. I should read the code more.

2. The reads are not behind the lock.
if (inited)
{
  use foo;
}
else
{
  lock
  {
     foo = …
     inited = true
  }

is racy if foo is not a pointer.

**Comment by nagytech** [comment]
> 1. Why is try/finally preferred? Do you want retry upon failure, or sticky failure, and is failure well handled either way? Try/finally makes failure sticky. I should read the code more.

In the original code, an exception on initialisation may fail to fully initialise, but will leave the class in an initialised state (since `inited = true` will always be set).  After I've moved the `inited = true` statement to the end of the block, the addition of `try/finally` retains that behaviour.  

> 2. The reads are not behind a lock?

From what I can see, all reads and writes to the uninitialised class will be gated at the lock until the class is initialised.  After `inited = true`, the lock is not considered for any further operations, so it's a transient gate and is almost insignificantly short lived.  I admit there's some racy-ness here, but all of it would have existed before my changes.

I did consider refactoring the class, but I think that would be a separate issue given the greater surface area.

**Comment by steveisok** [comment]
I think it's fine for the issue @nagytech is trying to solve.  I agree that refactoring is a separate effort.

**Comment by jaykrell** [comment]
The code is racy, and fails as a result, and the fix to keep it racy, just less so?

**Comment by nagytech** [comment]
@jaykrell 

> The code is racy, and fails as a result, and the fix is to keep it racy, just less so? Is that right?

In general, yes.  But, more specifically I would say that there are two distinct behaviours here:

1. The initialisation of `TermInfoDriver` is racy, and fails as a result, and the fix is to remove the racy aspect of the initialisation - which I've done; and

2. The post-initialized behaviour of `TermInfoDriver` is racy, and the fix would be best dealt with separately.

**Comment by steveisok** [comment]
@monojenkins build failed

**Comment by steveisok** [comment]
@monojenkins backport 2019-12
