### PR TITLE
[corlib] Silence undocumented exceptions in ReadXdgUserDir

### LINKED ISSUE #18652: Environment.GetFolderPath throws undocumented exception
## Steps to Reproduce

1. Remove read permissions on `~/.config/user-dirs.dirs` 
2. `Environment.GetFolderPath(Environment.SpecialFolder.Templates)`

### Current Behavior

An exception is thrown, but it is not [documented](https://docs.microsoft.com/en-us/dotnet/api/system.environment.getfolderpath?view=netframework-4.8)

### Expected Behavior

It only throws documented exceptions.

## On which platforms did you notice this

[*] macOS
[ ] Linux
[ ] Windows

**Version Used**:
Mono JIT compiler version 6.8.0.104 (2019-10/1cca0cfebfc Tue Jan 28 09:49:56 EST 2020)

## Stacktrace

```
System.UnauthorizedAccessException
Access to the path "/Users/$USER/.config/user-dirs.dirs" is denied.

System.IO.FileStream..ctor(String,FileMode,FileAccess,FileShare,Int32,Boolean,FileOptions)
System.IO.FileStream..ctor(String,FileMode,FileAccess,FileShare,Int32,FileOptions)
System.IO.StreamReader..ctor(String,Encoding,Boolean,Int32)
System.IO.StreamReader..ctor(String,Boolean)
System.IO.StreamReader..ctor(String)
System.Environment.ReadXdgUserDir(String,String,String,String)
System.Environment.UnixGetFolderPath(SpecialFolder,SpecialFolderOption)
System.Environment.GetFolderPath(SpecialFolder,SpecialFolderOption)
System.Environment.GetFolderPath(SpecialFolder)
```

### PR DESCRIPTION
**Pull request by mdh1418**
Fixes #18652 

```
Mitchells-iMac:mono mdhwang$ ls -al ~/.config/user-dirs.dirs
----------  1 mdhwang  staff  0 Feb  3 11:52 /Users/mdhwang/.config/user-dirs.dirs
Mitchells-iMac:mono mdhwang$ mcs Hello.cs && mono Hello.exe

GetFolderPath: /Users/mdhwang/Templates
```

### CODE REVIEW

File: mcs/class/corlib/System/Environment.cs [hunk 1]
```diff
@@ -587,10 +587,6 @@ private static string ReadXdgUserDir (string config_dir, string home_dir, string
 
 			string user_dirs_path = Path.Combine (config_dir, "user-dirs.dirs");
 
-			if (!File.Exists (user_dirs_path)) {
-				return Path.Combine (home_dir, fallback);
-			}
-
```
Comment (akoeplinger) [inline mcs/class/corlib/System/Environment.cs]: we should keep this check because not having the file is very common and we shouldn't be throwing an exception if we can avoid it (makes it harder to debug with first-chance exceptions turned on in the IDE or noisy if you're tracing all exceptions on the command line).

**Comment by mdh1418** [comment]
@monojenkins build failed

**Comment by mdh1418** [comment]
@monojenkins build failed

**Comment by mdh1418** [comment]
@monojenkins build
