### PR TITLE
[netcore] Enable netcore resolution logic for mono_assembly_byname_lookup

### LINKED ISSUE #15081: [netcore] Make System.Resources.Tests.ResourceManagerTests.GetString_ExpectEvents Pass
The test currently fails with:

```
System.Resources.Tests.ResourceManagerTests.GetString_ExpectEvents [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:
        
        Child exception:
          Xunit.Sdk.EqualException: Assert.Equal() Failure
        Expected: 2
        Actual:   0
           at System.Resources.Tests.ResourceManagerTests.Remote_ExpectEvents()
           at System.Resources.Tests.ResourceManagerTests.<>c.<GetString_ExpectEvents>b__10_0()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
        
        Child process:
          System.Resources.ResourceManager.Tests, Version=4.1.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Resources.Tests.ResourceManagerTests+<>c Void <GetString_ExpectEvents>b__10_0()
```

The thought is that netcore is missing assembly resolve events on AppDomain and AssemblyLoadContext.  Determine if that's the case and make the test pass.

### PR DESCRIPTION
**Pull request by CoffeeFlux**
Draft for now, as things are ~~probably~~definitely broken.

Addresses parts of #16246.
FIxes #15081.

Remaining todos:
- [x] Fix legacy behavior
- [ ] Figure out exact conditions under which the postload hook should be run
- [x] Rebase and resolve conflicts
- [x] Ensure the only caller of `netcore_load_reference` is `mono_assembly_request_byname`

### CODE REVIEW

File: mono/metadata/assembly.c [hunk 1]
```diff
@@ -4662,14 +4671,21 @@ mono_assembly_request_byname (MonoAssemblyName *aname, const MonoAssemblyByNameR
...
+	result = mono_assembly_request_byname_nosearch (aname, req, status);
 	const gboolean refonly = req->request.asmctx == MONO_ASMCTX_REFONLY;
 
 	if (!result && !req->no_postload_search) {
 		/* Try a postload search hook */
 		result = mono_assembly_invoke_search_hook_internal (req->request.alc, req->requesting_assembly, aname, refonly, TRUE);
 		result = prevent_reference_assembly_from_running (result, refonly);
 	}
+#else
+	result = netcore_load_reference (aname, req->request.alc, req->requesting_assembly, !req->no_postload_search);
```
Comment (lambdageek) [inline mono/metadata/assembly.c]: What do you think about getting rid of `netcore_load_reference` entirely and replacing its other callers by a call to `mono_assembly_request_byname`?

Comment (CoffeeFlux) [reply mono/metadata/assembly.c]: It's definitely an option. I'm not super happy with what the call stack looks like right now (since it's somewhat convoluted) but I also don't really want to require building a bunch more requests for simple calls within assembly.c, so I've been trying to think on how I want to organize things.

**Comment by CoffeeFlux** [comment]
I've decided to hold off on System.Tests.AppDomainTests.AssemblyResolveInvalidAssemblyName until a later PR, since other work is being done to reflection to pass along an ALC. The core issue is that when calling `Type.GetType()`, we end up in `type_from_parsed_name()`, which does not set a requesting_assembly despite firing off the postload hook. It should call byname directly and make sure to set that as well as the ALC. This will maybe combine well with wiring up the TypeResolved event.

**Comment by CoffeeFlux** [comment]
Rebased version on netcore is hitting a stack overflow. Oops.

**Comment by CoffeeFlux** [comment]
Ah, it was me not being careful about resolving conflicts.

File: netcore/System.Private.CoreLib/src/System.Runtime.Loader/AssemblyLoadContext.cs [hunk 2]
```diff
@@ -134,5 +134,53 @@ internal static Assembly DoAssemblyResolve (string name)
...
+			return null;
+		}
+#endregion
+#region Copied from AssemblyLoadContext.CoreCLR.cs, modified until our AssemblyBuilder implementation is functional
+		private static RuntimeAssembly? GetRuntimeAssembly(Assembly? asm)
+		{
+			return
+				asm == null ? null :
+				asm is RuntimeAssembly rtAssembly ? rtAssembly :
+				//asm is System.Reflection.Emit.AssemblyBuilder ab ? ab.InternalAssembly :
```
Comment (lambdageek) [inline netcore/System.Private.CoreLib/src/System.Runtime.Loader/AssemblyLoadContext.cs]: Is the only issue that we don't have an `InternalAssembly` property? could we add one that throws NIE and a FIXME to note to come back to it?

File: netcore/CoreFX.issues.rsp [hunk 3]
```diff
@@ -382,7 +382,7 @@
 
 # TODO: Missing assembly resolve events on AppDomain and AssemblyLoadContext
 # https://github.com/mono/mono/issues/15081
--nomethod System.Resources.Tests.ResourceManagerTests.GetString_ExpectEvents
+#-nomethod System.Resources.Tests.ResourceManagerTests.GetString_ExpectEvents
```
Comment (lambdageek) [inline netcore/CoreFX.issues.rsp]: Can delete this line and the two above it, no?

Comment (CoffeeFlux) [reply netcore/CoreFX.issues.rsp]: Yeah all that'll get deleted before I mark this as ready. I just leave things commented while working.

File: mono/metadata/assembly.c [hunk 4]
```diff
@@ -1669,6 +1672,13 @@ netcore_load_reference (MonoAssemblyName *aname, MonoAssemblyLoadContext *alc, M
 	if (reference)
 		goto leave;
 
+	// See: https://github.com/dotnet/coreclr/blob/0a762eb2f3a299489c459da1ddeb69e042008f07/src/vm/appdomain.cpp#L5178-L5239
+	if (!(strcmp (aname->name, MONO_ASSEMBLY_CORLIB_NAME) == 0 && is_satellite) && postload) {
```
Comment (CoffeeFlux) [inline mono/metadata/assembly.c]: I'm still unsure on under what conditions postload should be set or not, but maybe it's best to get this merged and fix issues as they come up about it being run when it shouldn't? I'll take another look at CoreCLR tomorrow and see if it's clearer to me.

File: netcore/System.Private.CoreLib/src/System.Runtime.Loader/AssemblyLoadContext.cs (hunk 2 above)
Comment (CoffeeFlux) [reply netcore/System.Private.CoreLib/src/System.Runtime.Loader/AssemblyLoadContext.cs]: I can do that if we're sure we want to use an InternalAssemblyBuilder the same way CoreCLR has. See: https://github.com/dotnet/coreclr/blob/52651008a5fb72eb678467cd2eb42aac4e5334e8/src/System.Private.CoreLib/src/System/Reflection/Emit/AssemblyBuilder.cs#L33

**Comment by filipnavara** [comment]
> Addresses parts of #16256.

Self-reference? Was this supposed to be different number?

**Comment by CoffeeFlux** [comment]
Yep, oops. Fixed.

File: netcore/System.Private.CoreLib/src/System.Runtime.Loader/AssemblyLoadContext.cs (hunk 2 above)
Comment (lambdageek) [reply netcore/System.Private.CoreLib/src/System.Runtime.Loader/AssemblyLoadContext.cs]: I see.  Well then I guess we'll have to come back here when we work on SRE for netcore.

**Comment by lambdageek** [comment]
@monojenkins build failed

File: netcore/System.Private.CoreLib/src/System.Runtime.Loader/AssemblyLoadContext.cs (hunk 2 above)
Comment (CoffeeFlux) [reply netcore/System.Private.CoreLib/src/System.Runtime.Loader/AssemblyLoadContext.cs]: Yeah, looking at it again I think the best option here is to not move this function to shared yet so we don't play ping-pong with the code, then re-evaluate at a later date. I'll update the comment to be clearer though.

**Comment by CoffeeFlux** [comment]
```
using System;
using System.Globalization;
using System.Resources;
using System.Runtime.Loader;
using System.Reflection;

namespace HelloWorld
{
    class Program
    {
        static System.Reflection.Assembly AssemblyResolveEventHandler(object sender, ResolveEventArgs args)
        {
            Console.WriteLine(sender == null);
            Console.WriteLine(AppDomain.CurrentDomain == sender);
            return null;
        }

        static void Main(string[] args)
        {
            Console.WriteLine("starting");
            AppDomain.CurrentDomain.AssemblyResolve += new ResolveEventHandler(AssemblyResolveEventHandler);
            ResourceManager resourceManager = new ResourceManager(typeof(Program));
            var culture = new CultureInfo("af-ZA");
            string actual = resourceManager.GetString("One", culture);
        }
    }
}
```
Output of this branch:
```
starting
False
True
False
```
.NET Core output:
```
starting
True
False
True
False
```
There are a couple other scenarios where the sender/requesting assembly seems to be set more aggressively here than in .NET Core. Somewhat amusingly, the AssemblyResolve event seems to almost always be triggered, which is what I was originally trying to test here, so I'm actually less worried about that for the moment.

**Comment by CoffeeFlux** [comment]
Oh, maybe scratch that? I'm getting output like ours on preview8 - I was using preview6 before.

**Comment by CoffeeFlux** [comment]
This is still different on preview8 though:
```
using System;
using System.Globalization;
using System.Resources;
using System.Runtime.Loader;
using System.Reflection;

namespace HelloWorld
{
    class Program
    {
        static System.Reflection.Assembly AssemblyResolveEventHandler(object sender, ResolveEventArgs args)
        {
            Console.WriteLine(args.RequestingAssembly != null);
            return null;
        }

        static void Main(string[] args)
        {
            Console.WriteLine("starting");
            AppDomain.CurrentDomain.AssemblyResolve += new ResolveEventHandler(AssemblyResolveEventHandler);
            AssemblyLoadContext.Default.LoadFromAssemblyName (new AssemblyName ("asdf"));
        }
    }
}
```
Us:
```
starting
True
```
Core:
```
starting
False
```

**Comment by CoffeeFlux** [comment]
I think we're okay to merge this, and then I'll clarify/attempt to fix when we set RequestingAssembly in a followup PR. I'm still also unsure of whether AssemblyResolve should be triggered when resolving references, but in a similar vein I think we're better off getting this merged and dealing with issues as they come up.

**Comment by CoffeeFlux** [comment]
@monojenkins build failed

**Comment by CoffeeFlux** [comment]
[This](https://docs.microsoft.com/en-us/dotnet/api/system.resolveeventargs.requestingassembly?view=netcore-3.0#remarks) seems to be the main documentation on when RequestingAssembly should or should not be set.
