### PR TITLE
[mini] Don't inline methods if they're going to be instrumented for coverage.

### LINKED ISSUE #6186: Code coverage instrumentation logic should deal with inlining the same way as enter/leave instrumentation
That is, `mono_method_check_inlining` should fail if `method` has coverage instrumentation enabled.

### PR DESCRIPTION
**Pull request by alexrp**
This handles coverage instrumentation in a similar fashion to call instrumentation.

Fixes #6186.

### CODE REVIEW

File: mono/mini/method-to-ir.c [hunk 1]
```diff
@@ -7273,12 +7276,14 @@ mono_method_to_ir (MonoCompile *cfg, MonoMethod *method, MonoBasicBlock *start_b
...
+		if (cfg->compile_aot)
+			g_error ("Coverage profiling is not supported with AOT.");
+
 		cfg->coverage_info = mono_profiler_coverage_alloc (cfg->method, header->code_size);
-	if (cfg->compile_aot && cfg->coverage_info)
-		g_error ("Coverage profiling is not supported with AOT.");
+	}
 
-	if ((cfg->gen_sdb_seq_points && cfg->method == method) || cfg->coverage_info) {
+	if (cfg->gen_sdb_seq_points || cfg->prof_coverage) {
```
Comment (vargaz) [inline mono/mini/method-to-ir.c]: This changes the logic for the non-profiler case as well.

Comment (alexrp) [reply mono/mini/method-to-ir.c]: Fixed.

**Comment by alexrp** [comment]
Failures unrelated.

**Comment by alexrp** [comment]
@monojenkins build failed

**Comment by alexrp** [comment]
@monojenkins build failed

File: mono/mini/method-to-ir.c [hunk 2]
```diff
@@ -7273,12 +7276,14 @@ mono_method_to_ir (MonoCompile *cfg, MonoMethod *method, MonoBasicBlock *start_b
 		seq_points = FALSE;
 	}
 
-	if (cfg->method == method)
+	if (cfg->prof_coverage) {
+		if (cfg->compile_aot)
```
Comment (luhenry) [inline mono/mini/method-to-ir.c]: This could use `g_assertf`.
