### PR TITLE
Issue18826 fix

### LINKED ISSUE #18826: codesigned mkbundled executable never ends with xmonkeysloveplay
## Steps to Reproduce

1. create a self-contained application with mkbundle e.g. console app
2. codesign the self-contained application
3. run the signed app, but it shows mono usage

### Current Behavior

The codesigned application shows mono usage.

### Expected Behavior

The codesigned application runs as the same behavior as the mkbundled application.

According to the source code, mkbundled executable is expected to be terminated with `xmonkeysloveplay`.
https://github.com/mono/mono/blob/master/mono/mini/main.c#L182

However after codesigning, the executable is terminated with code signature. So it doesn't end with `xmonkeysloveplay` anymore.

I supposed to relocate code signature section by tweaking the binary, but it will break the signature verification. (I haven't tried though)

Possible solution would be to refer only string table section of the executable to find `xmonkeysloveplay`.

I appreciate any tentative solution to avoid the problem. Since codesign is required for notarization. Because of technical reason (to avoid app from crash), I need to use mkbundle.

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:
5.2.0, but it should happen on recent version too.

## Stacktrace
No stacktrace since it is expected behavior according to the source code.

```
Please paste the stack trace here if available.
```

### PR DESCRIPTION
**Pull request by HinTak**
Fixes #18826

### CODE REVIEW

**Comment by HinTak** [comment]
Apologies about the status toggle (accidentally removing the branch while doing some tidying)

**Comment by HinTak** [comment]
@monojenkins build

**Comment by ylatuya** [comment]
This patch seems to fix part of the issue, but the signed binary segfaults:
```
MONO_LOG_LEVEL=debug ./LongoMatch
Mono: Config attempting to parse: '/usr/local/etc/mono/config'.
Mono: Config attempting to parse: '/Users/foo/.mono/config'.
[1]    28631 segmentation fault  MONO_LOG_LEVEL=debug ./LongoMatch
```

I am also unable to run lldb on that binary (mono also fails with the same issue), so it's impossible to know what's failing:
```
 lldb --  ./LongoMatch
(lldb) target create "./LongoMatch"
Current executable set to '/Users/foo/git/vasone/package/macOS/app/LongoMatch.app/Contents/MacOS/LongoMatch' (x86_64).
(lldb) r
error: process exited with status -1 (Error 1)
```

**Comment by HinTak** [comment]
Can you zip and attach your `./LongoMatch`?

**Comment by ylatuya** [comment]
> This patch seems to fix part of the issue, but the signed binary segfaults:
The segfault was unrelated with the path, I can therefore confirm that the following patch fixes the issue finding "xmonkeysloveplay" after codesigning the binary

**Comment by HinTak** [comment]
The mac gui in https://github.com/HinTak/Font-Validator/releases/tag/FontVal-2.1.6 was built with this patch, adjusted with the accompanying python script, then signed. People seem to be happy with it.

**Comment by akoeplinger** [comment]
@monojenkins build

**Comment by dfernandezramos** [comment]
@akoeplinger Any news on someone from runtime team that can move forward this fix?

**Comment by ylatuya** [comment]
Can anyone please review this patch? It's impossible to notarize macOS application without this fix.

**Comment by CoffeeFlux** [comment]
I'll get to it later today. Sorry for the delay.

**Comment by HinTak** [comment]
As I mentioned earlier, the latest release of FontVal (2.1.6) was built with this patch, mkbundled, and adjusted with the accompanying python script after mkbundle, signed and notarized (the signing and motorisation was done by a trusted collaborator - I only did all the other parts). People seem to be happy with the outcome so far (github statssays a few tens of copies are downloaded - it is a specialist app so this is normal ) and I have not received any complaints. FYI

**Comment by HinTak** [comment]
Ideally the functionality of the accompanying post-mkbundle adjustment python script should be included with mkbundle.

File: mono/mini/main.c [hunk 1]
```diff
@@ -179,8 +182,49 @@ probe_embedded (const char *program, int *ref_argc, char **ref_argv [])
 		goto doclose;
 	if (read (fd, sigbuffer, sizeof (sigbuffer)) == -1)
 		goto doclose;
-	if (memcmp (sigbuffer+sizeof(uint64_t), "xmonkeysloveplay", 16) != 0)
+	if (memcmp (sigbuffer+sizeof(uint64_t), "xmonkeysloveplay", 16) == 0)
+		goto found;
+	else
```
Comment (CoffeeFlux) [inline mono/mini/main.c:187]: There's no need to put all this in an else block, just pull it out.

File: mono/mini/main.c [hunk 2]
```diff
@@ -179,8 +182,49 @@ probe_embedded (const char *program, int *ref_argc, char **ref_argv [])
...
+	{
+#ifdef HOST_DARWIN
+		struct mach_header_64 h;
```
Comment (CoffeeFlux) [inline mono/mini/main.c:190]: Please use a more descriptive variable name than `h`. `header` or something is fine.

File: mono/mini/main.c [hunk 3]
```diff
@@ -179,8 +182,49 @@ probe_embedded (const char *program, int *ref_argc, char **ref_argv [])
...
+		if ((sigstart = lseek (fd, 0, SEEK_SET)) == -1)
+			goto doclose;
+		if (read (fd, &h, sizeof (h)) == -1)
+			goto doclose;
+		if (h.magic != MH_MAGIC_64)
+			goto doclose;
+
+		off_t total = h.sizeofcmds;
```
Comment (CoffeeFlux) [inline mono/mini/main.c:198]: A short explanation of what's going on in the code following here would be nice, since I believe a bunch of the stuff in this block is not documented by apple. It mostly makes sense to me, but I'm still hesitant to merge this without some sort of comment explaining it.

File: mono/mini/main.c [hunk 4]
```diff
@@ -179,8 +182,49 @@ probe_embedded (const char *program, int *ref_argc, char **ref_argv [])
...
+		uint32_t count = h.ncmds;
+		while (total > 0 && count >0) {
+			struct load_command lc;
+			off_t sig_stored = lseek (fd, 0, SEEK_CUR);
```
Comment (CoffeeFlux) [inline mono/mini/main.c:202]:
```suggestion
			off_t sig_stored = lseek (fd, 0, SEEK_CUR); // get current offset
```

File: mono/mini/main.c (hunk 1 above)
Comment (HinTak) [reply mono/mini/main.c:187]: Yes, there is - there is another `goto found` in the new code block. Basically the old code assume the xmonkeyloveplay is located at the end. The new code tries this first (the above block), and if not found, try harder by looking at the mac header and find it via the header from the tail end of the signature section.

Comment (HinTak) [reply mono/mini/main.c:187]: So the "found" section is now jumped to, from two places, instead of one.

**Comment by HinTak** [comment]
@CoffeeFlux ncmds = 20 for the 5.20/6.6/6.8 binaries I built with this patch a few weeks ago. I'll change the header variable "h" to something more descriptive, and perhaps add some comments while I am at it, soon.

File: mono/mini/main.c (hunk 3 above)
Comment (HinTak) [reply mono/mini/main.c]: I have added a few blocks of comments for clarity in https://github.com/mono/mono/pull/19580/commits/343151120e5940871febfda4b70df3b58df3af01

File: mono/mini/main.c (hunk 2 above)
Comment (HinTak) [reply mono/mini/main.c]: renamed "h" to "bin_header" in https://github.com/mono/mono/pull/19580/commits/0cc053706a8539e527cdb2410902f1bf7f77d9d7

File: mono/mini/main.c (hunk 1 above)
Comment (CoffeeFlux) [reply mono/mini/main.c:188]: https://gist.github.com/CoffeeFlux/6e68c33b9dfae5ce305ce358ec1d44d5 Why does this not work? Am I missing something?

File: mono/mini/main.c [hunk 5]
```diff
@@ -179,8 +182,65 @@ probe_embedded (const char *program, int *ref_argc, char **ref_argv [])
 		goto doclose;
 	if (read (fd, sigbuffer, sizeof (sigbuffer)) == -1)
 		goto doclose;
-	if (memcmp (sigbuffer+sizeof(uint64_t), "xmonkeysloveplay", 16) != 0)
+	// First, see if "xmonkeysloveplay" is at the end of file
+	if (memcmp (sigbuffer + sizeof (uint64_t), "xmonkeysloveplay", 16) == 0)
+		goto found;
+	else
+	{
+#ifdef HOST_DARWIN
```
Comment (CoffeeFlux) [inline mono/mini/main.c:190]: We only want this on MacOS, not iOS etc right? This define should be `TARGET_OSX`, sorry for not catching that earlier.

Comment (HinTak) [reply mono/mini/main.c:190]: That's what HOST_DARWIN does!

Comment (HinTak) [reply mono/mini/main.c:190]: Oh, I don't know about ipad / iphone / ios - do they also have a signing process?

Comment (CoffeeFlux) [reply mono/mini/main.c:190]: `HOST_DARWIN` covers all the Apple platforms: MacOS, iOS, tvOS, etc. The entrypoint for the mobile platforms is different and mkbundle doesn't exist for them, so this should only be on MacOS, and accordingly should use the `TARGET_OSX` define. I realize that's a switch from host to target, but that's an issue on our end with the define names (sorry!) and `TARGET_OSX` is what you want.

Comment (HinTak) [reply mono/mini/main.c]: Okay, done - https://github.com/mono/mono/commit/b1ca14f06aed4e1683a6e8cf04db4c2ddd502ea1 - the collection of HOST_* and TARGET_* are quite confusing, especially as WIN32/WIN64 exist for both! I know there are subtle differences regarding cross-compiling, nonetheless...

I think the new code is harmless on the other apple OSes, except for a small waste of cpu cycles.

Comment (CoffeeFlux) [reply mono/mini/main.c]: Yeah, for our AOT compiler cross-compiling is a supported scenario, so the HOST/TARGET difference matters in some cases. We should really fix up the OSX defines, though it's not particularly urgent.

**Comment by CoffeeFlux** [comment]
I think the only remaining issue on my end is the (purely stylistic) change of pulling the code out of the else block, see my previous comment and the updated snippet of what I mean.

Other than that, this looks good, and I've pinged two people more familiar with mkbundle to take a look before I merge. If they don't get a chance anytime soon I'll just merge it myself, but I want to give them at least a few business days. 😄 

Thanks again for contributing this!

File: mono/mini/main.c (hunk 1 above)
Comment (HinTak) [reply mono/mini/main.c:188]: Okay, I see. I guess it is a matter of style/preference: I don't like bare / unscoped `goto`'s. If I were to modify the code to your direction, I'd put a comment next to the bare `goto` something like `// did not find "..." at either of two places`, as a reminder.

The header scanning code is quite mac os x specific and have a few "local" variables, like the header structs, not used outside, so it is somewhat nice to put the code block in a {}, even with #defines to exclude it for other OSes.

But the two probably compile to identical codes.

Comment (CoffeeFlux) [reply mono/mini/main.c:188]: If you feel strongly about it that's fine - not my preference but it should ultimately product the same output.

**Comment by HinTak** [comment]
I have removed the else, and added a comment, but I like to keep the code block braces.

**Comment by marek-safar** [comment]
approve

**Comment by marek-safar** [comment]
@vargaz could you do review pass on this one

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by migueldeicaza** [comment]
I like the approach - I have not audited the parsing of the MachO file, and will not likely audit that, but like I said, I like the approach.

**Comment by CoffeeFlux** [comment]
@monojenkins backport to 2020-02
