### PR TITLE
[threading] embedded mono hangs

### LINKED ISSUE #14725: mono 5.20 hangs when called from native thread
I have a application that invokes mono from native code using threads.  Within the managed code it is utilizing generated code to access a soap web service.  This has been working initially implemented against mono 5.02 and was last working with mono 5.18.  With mono 5.20 I see it hanging when creating the soap client object; but only when called from an separate thread, which is calling mono_thread_attach.

## Steps to Reproduce

1. Run the uploaded example 'vSphereTest-Native' 
This is expected to fail as it cannot connect to the web service; It will first execute the managed code from the main thread which will return.  It will then start a thread and execute the same managed code which will get stuck in "Connecting..

[vSphereTest-Native.zip](https://github.com/mono/mono/files/3241224/vSphereTest-Native.zip)

### Current Behavior (output from test program with 5.20)

Starting!
MonoVersion = 5.20.1.19 (tarball)
Method: vSphereTestLibMono.vSphereTest:Test ()
Method: vSphereTestLibMono.vSphereTest:.ctor ()
Calling TestMethod
Connecting
Connected
Returned from TestMethod
thread running
threadArgs d = 0x556dd813aae0, c= 0x556dd81a5d18, obj = (nil)
Calling TestMethod
Connecting
^C <- hangs here

### Expected Behavior (Output from test program with 5.16)

Starting!
MonoVersion = 5.16.0.220 (tarball)
Method: vSphereTestLibMono.vSphereTest:Test ()
Method: vSphereTestLibMono.vSphereTest:.ctor ()
Calling TestMethod
Connecting
Connected
Returned from TestMethod
thread running
threadArgs d = 0x55905c1a9830, c= 0x55905c216d58, obj = (nil)
Calling TestMethod
Connecting
Connected
Returned from TestMethod
thread exiting
Complete!!

## On which platforms did you notice this

[ ] macOS
[X] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 5.20.1.19 (tarball Thu Apr 11 08:37:52 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(600)
        Suspend:       hybrid
        GC:            sgen (concurrent by default)

### LINKED ISSUE #16192: Embedded Mono hangs when using native threads
Embedded mono hangs when using native threads to call into a mono function that allocates semi-large chunks of memory. Fails for mono 5.20.1.34 and 6.0.0.319, but works for 5.18.0.268.

## Steps to Reproduce

A full demo example is provided in repo https://github.com/krixkrix/mono_thread_problem.
The demo was tested on linux.

The demo contains a simple C# function that allocates a memory block. 
```csharp
      public void Foo()
        {
            for (int i = 1; i<= 10; i++)
            {
                Console.WriteLine(String.Format("Allocate {0} of 10", i));
                byte[] pixels = new byte[1000000];  // size affects how soon the thread hangs
            }
            Console.WriteLine("Done");
            return;
        }
```
This function is called from managed code (c++) in different threads, but each call completes before the next.

### Current Behavior

The output of the test project is:

> This should call Foo a hundred times, but hangs...
> call Foo 0
> Allocate 1 of 10
> Allocate 2 of 10
> Allocate 3 of 10
> Allocate 4 of 10
> Allocate 5 of 10
> Allocate 6 of 10
> Allocate 7 of 10
> Allocate 8 of 10
> Allocate 9 of 10
> Allocate 10 of 10
> Done
> call Foo 1
> Allocate 1 of 10
> Allocate 2 of 10
> Allocate 3 of 10
> Allocate 4 of 10
> Allocate 5 of 10
> Allocate 6 of 10
> Allocate 7 of 10
> Allocate 8 of 10

- When called from different threads it will hang after some time.
- When called from a single thread it can go on forever.
- I notice that the size of memory allocation in the c# code matters.

This may relate to #14725

## On which platforms did you notice this

[ ] macOS
[x ] Linux, Ubuntu 18.04
[ ] Windows

**Version Used**:

Fails with: 
- mono 6.0.0.319
- mono 5.20.1.34

Works with:
- mono 5.18.0.268

c++ code:
g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

### PR DESCRIPTION
**Pull request by thaystg**
When embedded mono is executing a C++ code, it didn't start to execute a C# code, we don't need to suspend the thread to run GC.
So my idea is set the flag  MONO_THREAD_INFO_FLAGS_NO_GC when initializes mono embedded and only remove the flag MONO_THREAD_INFO_FLAGS_NO_GC when a mono_runtime_invoke_array or a mono_runtime_invoke is called. 

Fixes #16192
Fixes #14725

### CODE REVIEW

File: mono/mini/driver.c [hunk 1]
```diff
@@ -2754,7 +2754,9 @@ mono_main (int argc, char* argv[])
 MonoDomain * 
 mono_jit_init (const char *file)
 {
-	return mini_init (file, NULL);
+	MonoDomain *ret = mini_init (file, NULL);
+	MONO_ENTER_GC_SAFE_UNBALANCED;
```
Comment (lambdageek) [inline mono/mini/driver.c]: I think we need a comment here to explain why we want to leave this thread in GC Safe mode.

File: mono/mini/driver.c [hunk 2]
```diff
@@ -2780,7 +2782,9 @@ mono_jit_init (const char *file)
 MonoDomain * 
 mono_jit_init_version (const char *domain_name, const char *runtime_version)
 {
-	return mini_init (domain_name, runtime_version);
+	MonoDomain *ret = mini_init (domain_name, runtime_version);
+	MONO_ENTER_GC_SAFE_UNBALANCED;
```
Comment (lambdageek) [inline mono/mini/driver.c]: Also a comment here.

File: mono/utils/mono-threads-api.h [hunk 3]
```diff
@@ -130,13 +130,11 @@ For further explanation of what can and can't be done in GC unsafe mode:
...
 
 #define MONO_ENTER_GC_SAFE_UNBALANCED	\
-	do {	\
 		MONO_STACKDATA (__gc_safe_unbalanced_dummy); \
 		gpointer __gc_safe_unbalanced_cookie = mono_threads_enter_gc_safe_region_unbalanced_internal (&__gc_safe_unbalanced_dummy)
 
 #define MONO_EXIT_GC_SAFE_UNBALANCED	\
-		mono_threads_exit_gc_safe_region_unbalanced_internal (__gc_safe_unbalanced_cookie, &__gc_safe_unbalanced_dummy);	\
-	} while (0)
+		mono_threads_exit_gc_safe_region_unbalanced_internal (__gc_safe_unbalanced_cookie, &__gc_safe_unbalanced_dummy);
```
Comment (lambdageek) [inline mono/utils/mono-threads-api.h]: it seems like this macro has almost no value: it won't compile unless you pair it with `MONO_ENTER_GC_SAFE_UNBALANCED` (because it needs the cookie).  But if you use it like that, it's balanced!

**Comment by thaystg** [comment]
> 3\. MONO_EXIT_GC_SAFE_UNBALANCED

1) Okay
2) mono_jit_init_version is used in some tests like: mono/unit-tests/test-mono-string.c and mono/unit-tests/test-mono-callspec.c
3) Okay

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
@monojenkins build failed
