### PR TITLE
[debugger] Fix exception handler in a new thread and fix MONO_DEBUG=suspend-on-unhandled

### LINKED ISSUE #16588: mono does not suspend on unhandled exception
## Steps to Reproduce

1. Code
```csharp
using System;

namespace Test
{
  class MainClass
  {
    public static void Main(string[] args)
    {
      throw new Exception("blabla");
    }
  }
}
```
2. Run:
MONO_DEBUG=suspend-on-unhandled mono ./Test.exe

### Current Behavior

Unhandled Exception:
System.Exception: blabla
  at Test.MainClass.Main (System.String[] args) [0x00001] in <36e3bc63485340bfbb0ade4f561e1edc>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.Exception: blabla
  at Test.MainClass.Main (System.String[] args) [0x00001] in <36e3bc63485340bfbb0ade4f561e1edc>:0

and then mono process ends.

### Expected Behavior

mono process should suspend so I can attach to it for example with gdb.

## On which platforms did you notice this

[ ] macOS
[*] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 6.0.0.327 (tarball Thu Aug 29 21:19:42 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(600)
        Suspend:       hybrid
        GC:            sgen (concurrent by default)

### LINKED ISSUE #17601: [debugger] When debugger encounters a unhandled exception, it doesn't stop
```csharp
using System;
using System.Linq;
using System.Collections.Generic;
using System.Net.Sockets;
using System.Threading.Tasks;
using System.Threading;
namespace TestResolveCSharpConsole
{
   class MainClass
   {
       public static void Main(string[] args)
       {
           try
           {
               Thread thread = new Thread(SecondFoo);
               thread.Start();
               thread.Join()
           }
           catch (Exception sockEx)
           {
               Console.WriteLine(“correctly handled”);
           }
       }
       public static void SecondFoo()
       {
           throw new Exception(“Error”);
       }
   }
}
```

Current Behavior using Hybrid Suspension:
Don't stop at uncaught exception:  throw new Exception(“Error”);

Expected Behavior:
Stop at uncaught exception:  throw new Exception(“Error”);

### PR DESCRIPTION
**Pull request by thaystg**
The behaviour expected of filter exceptions is:
-> throw in a async task with a try catch in the caller -> don't stop
-> throw in a new thread with a try catch in the caller -> stop
-> throw in the main thread without any try catch -> stop

Including a new test to test the fix of #17601.

Fixing #16588, create a while 1 to stops the program execution when an exception is thrown and no try catch is found and MONO_DEBUG=suspend-on-unhandled.

Fixes #17601
Fixes #16588

### CODE REVIEW

File: mono/mini/debugger-agent.c [hunk 1]
```diff
@@ -5204,6 +5205,12 @@ static void
 debugger_agent_handle_exception (MonoException *exc, MonoContext *throw_ctx,
 									  MonoContext *catch_ctx, StackFrameInfo *catch_frame)
 {
+	if (catch_ctx == NULL && catch_frame == NULL && mini_debug_options.suspend_on_unhandled && mono_object_class (exc) != mono_defaults.threadabortexception_class) {
+		mono_runtime_printf_err ("Unhandled exception, suspending...");
+		while (1)
+			;
+	}
```
Comment (lambdageek) [inline mono/mini/debugger-agent.c]: If the loop is here, doesn't that mean that `suspend-on-unhandled` will only be triggered when we start with debugging?   I think `suspend-on-unhandled` is supposed to work even without the debugger enabled.

Comment (thaystg) [reply mono/mini/debugger-agent.c]: I don't think so. I've tested using this command line:
- MONO_DEBUG=suspend-on-unhandled ./mono/mini/mono-sgen test16588.exe
And suspend-on-unhandled was triggered.

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
@monojenkins build OS X x64 Android SDK

**Comment by lambdageek** [comment]
@monojenkins build

(the `__chk_fail` thing on Android SDK should be fixed by  #18308)

**Comment by lambdageek** [comment]
@monojenkins build

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
@monojenkins backport 2019-12
