### PR TITLE
Protecting boxing a null value

### LINKED ISSUE #13969: (regression) SIGSEGV in RuntimeMethodInfo:InternalInvoke with xunit
Environment: 
Ubuntu 16.04 Azure Pipelines image with
`Mono JIT compiler version 5.18.0.268 (tarball Thu Feb 28 15:29:06 UTC 2019)`

was working completely fine with 
`Mono JIT compiler version 5.18.0.240 (tarball Wed Jan 16 09:13:03 UTC 2019)`

Repro:
```
git clone --recursive git@github.com:AvaloniaUI/Avalonia.git
cd Avalonia
sudo apt-get update && sudo apt-get install castxml
dotnet tool install --global Nuke.GlobalTool --version 0.12.3
nuke --target CiAzureLinux --configuration=Release
```

One of xunit test assemblies segfaults like this https://dev.azure.com/AvaloniaUI/AvaloniaUI/_build/results?buildId=1851&view=logs&jobId=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&taskId=d9b15392-e4ce-5e4c-0c8c-b69645229181&lineStart=1132&lineEnd=1133&colStart=1&colEnd=1

I've also checked with mono built from master, still segfaults, but I'm also seeing messages like these:
```
ves_icall_TypeBuilder_create_runtime_class_raw USED 151 handles
ves_icall_TypeBuilder_create_runtime_class_raw USED 156 handles
ves_icall_TypeBuilder_create_runtime_class_raw USED 104 handles
ves_icall_TypeBuilder_create_runtime_class_raw USED 108 handles
ves_icall_TypeBuilder_create_runtime_class_raw USED 158 handles
```

Not sure if that's relevant.

Also reproduced on OSX with `MonoFramework-MDK-5.18.0.268.macos10.xamarin.universal.pkg`, works fine with 5.18.0.225.

### PR DESCRIPTION
**Pull request by thaystg**
Trying to box a null value crashes inside mono_gc_wbarrier_value_copy_internal. As described by the customer using version 5.18.0.240 the crash doesn't happen.

As I could debug using this version doesn't crash only because is ignoring the SIGSEGV, when I attach to LLDB I can see the same crash in both versions.
I protected to only add data to res_handle if there is a valid value.
Fixes #13969

### CODE REVIEW

File: mono/metadata/object.c [hunk 1]
```diff
@@ -6946,37 +6946,38 @@ mono_value_box_handle (MonoDomain *domain, MonoClass *klass, gpointer value, Mon
...
-			*(guint16 *)(data) = *(guint16 *) value;
-			break;
-		case 4:
-			*(guint32 *)(data) = *(guint32 *) value;
-			break;
-		case 8:
-			*(guint64 *)(data) = *(guint64 *) value;
-			break;
-		default:
+	if (value != NULL) {
```
Comment (lambdageek) [inline mono/metadata/object.c]: So if the source value is null we return a result with some default contents?  That seems easy to use incorrectly.  

Can we assert in here that `value != NULL` and fix the callers instead?  or maybe there is some managed exception that we should throw?

**Comment by thaystg** [comment]
@monojenkins build failed

File: mcs/class/corlib/Test/System.Reflection/MethodInfoTest.cs [hunk 2]
```diff
@@ -658,6 +658,15 @@ public void NullableTests ()
 			Assert.AreEqual (10, pi2.GetGetMethod ().Invoke (10, null));
 		}
 
+		[Test]
+		public void NullableTestsStatic ()
+		{
+			Nullable<Double> val = new Nullable<Double>(new Double());
+			MethodInfo mi = typeof (Nullable<Double>).GetMethod ("op_Implicit");
+            object obj = val;
```
Comment (lambdageek) [inline mcs/class/corlib/Test/System.Reflection/MethodInfoTest.cs]: Indentation

File: mono/metadata/object.c [hunk 3]
```diff
@@ -6928,6 +6931,7 @@ mono_value_box_handle (MonoDomain *domain, MonoClass *klass, gpointer value, Mon
 	error_init (error);
 
 	g_assert (m_class_is_valuetype (klass));
+	g_assert (value != NULL);
```
Comment (lambdageek) [inline mono/metadata/object.c]: 🎉

File: mono/metadata/object.c [hunk 4]
```diff
@@ -6937,6 +6941,7 @@ mono_value_box_handle (MonoDomain *domain, MonoClass *klass, gpointer value, Mon
 	if (mono_class_is_nullable (klass))
 		return mono_nullable_box_handle (value, klass, error);
 
+
```
Comment (lambdageek) [inline mono/metadata/object.c]: Stray whitespace change

File: mono/metadata/object.c [hunk 5]
```diff
@@ -6946,7 +6951,7 @@ mono_value_box_handle (MonoDomain *domain, MonoClass *klass, gpointer value, Mon
 	return_val_if_nok (error, NULL_HANDLE);
 
 	size -= MONO_ABI_SIZEOF (MonoObject);
-
+
```
Comment (lambdageek) [inline mono/metadata/object.c]: Stray whitespace

File: mono/metadata/object.c [hunk 6]
```diff
@@ -6978,6 +6983,7 @@ mono_value_box_handle (MonoDomain *domain, MonoClass *klass, gpointer value, Mon
 #endif
 		MONO_EXIT_NO_SAFEPOINTS;
 	}
+
```
Comment (lambdageek) [inline mono/metadata/object.c]: Stray whitespace.

File: mono/metadata/object.c (hunk 3 above)
Comment (alexischr) [inline mono/metadata/object.c]: @lambdageek  This assert would be nice to have on 2019-02. Maybe you have already proved me wrong but I still suspect `[MemberData]` getting into trouble using reflection to transform C# tuples to argument lists.

Comment (lambdageek) [reply mono/metadata/object.c]: @alexischr Can you point us at an example of the tuples transformation? Sounds like another interesting test case.

**Comment by lambdageek** [comment]
@monojenkins backport to 2019-04
@monojenkins backport to 2019-02
@monojenkins backport to 2018-10

**Comment by thaystg** [comment]
> @lambdageek backporting to 2018-10 failed, the patch results in conflicts:
> 
> ```
> Applying: Trying to box a null value crashes inside mono_gc_wbarrier_value_copy_internal. As described by the customer using version 5.18.0.240 the crash doesn't happen. As I could debug using this version doesn't crash only because is ignoring the SIGSEGV, when I attach to LLDB I can see the same crash in both versions. I protected to only add data to res_handle if there is a valid value. Fixes #13969
> Using index info to reconstruct a base tree...
> M	mono/metadata/object.c
> .git/rebase-apply/patch:40: trailing whitespace.
> 	if (value != NULL) { 
> warning: 1 line adds whitespace errors.
> Falling back to patching base and 3-way merge...
> Auto-merging mono/metadata/object.c
> CONFLICT (content): Merge conflict in mono/metadata/object.c
> error: Failed to merge in the changes.
> Patch failed at 0001 Trying to box a null value crashes inside mono_gc_wbarrier_value_copy_internal. As described by the customer using version 5.18.0.240 the crash doesn't happen. As I could debug using this version doesn't crash only because is ignoring the SIGSEGV, when I attach to LLDB I can see the same crash in both versions. I protected to only add data to res_handle if there is a valid value. Fixes #13969
> ```
> Please backport manually!

@lambdageek, should I do it manually?

**Comment by thaystg** [comment]
@monojenkins build Linux AArch64 Interpreter

**Comment by lambdageek** [comment]
@thaystg yes, please make a 2018-10 backport.

it might be easier to cherrypick the commit if you first rewrite it on a local branch to squash all the changes together - I think the two older commits are probably conflicting with something on the 2018-10 branch.

**Comment by thaystg** [comment]
@monojenkins build Linux x64 Coop Suspend

File: mono/metadata/object.c (hunk 3 above)
Comment (alexischr) [reply mono/metadata/object.c]: @lambdageek Unfortunately that was back in the summer, I don't remember any details. Digging into the source brought it back (it was params object[]): https://github.com/xunit/xunit/commit/ff6ecaaf4df79f4266e7d2ab24493e49a5133031#diff-c6cbc959191da11fa205494c2731efe9L27 . Some of those methods look great for testing :)

**Comment by thaystg** [comment]
@monjenkins build Linux AArch64 Coop Suspend

**Comment by thaystg** [comment]
@monjenkins build Linux AArch64 Coop Suspend

**Comment by thaystg** [comment]
@monojenkins build failed
