### PR TITLE
Switch supported runtimes storage from an array to a list

### LINKED ISSUE #12141: Too many supportedRuntime tags in exe.config file cause problems on Windows
## Steps to Reproduce
1. Using a "Hello World type Console program set the relevant exe.config to the following on windows, using Production release Mono 5.16 ( 32 Bit and 64 Bit)
```
<?xml version="1.0"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7" />
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" />
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.1" />
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5" />
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.0"/>
  </startup>
</runtime>
 

</configuration>
```

### Current Behavior
Application does not display any output, and does not launch.

### Expected Behavior
Application will Display "Hello World"

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[X] Windows

**Version Used**:
(5.16.0.220)

### PR DESCRIPTION
**Pull request by CoffeeFlux**
Fixes #12141 

Switched to a list because in theory any number of tags can be present. Old behavior was to put them into an array of size 3 and zero the byte following them, which was causing the crash with more than two tags. There's no null check for the default runtime because that should never happen, and the list is reversed to preserve the order from the XML. Changing the signature of `get_runtimes_from_exe` should be fine because it's static and only called in the one place.

### CODE REVIEW

File: mono/metadata/domain.c [hunk 1]
```diff
@@ -573,26 +572,27 @@ mono_init_internal (const char *filename, const char *exe_filename, const char *
...
+		runtimes = g_slist_prepend (runtimes, (gpointer)default_runtime);
 		g_print ("WARNING: The runtime version supported by this application is unavailable.\n");
 		g_print ("Using default runtime: %s\n", default_runtime->runtime_version); 
 	}
 
 	/* The selected runtime will be the first one for which there is a mscrolib.dll */
-	for (n = 0; runtimes [n] != NULL && ass == NULL; n++) {
-		current_runtime = runtimes [n];
+	GSList *tmp = runtimes;
+	while (tmp != NULL) {
```
Comment (Therzok) [inline mono/metadata/domain.c]: g_slist_foreach?

Comment (CoffeeFlux) [reply mono/metadata/domain.c]: I'm not sure a new function is really necessary considering how short this is, and it's not like C has anonymous functions. I can change it if you think there's a good reason to, though.

Comment (CoffeeFlux) [reply mono/metadata/domain.c]: Actually looking again, I think foreach would further complicate the logic thanks to the break, so I'm inclined to say it's definitely not the way to go.

Comment (Therzok) [reply mono/metadata/domain.c]: > I can change it if you think there's a good reason to, though.

Was just wondering. Yeah, I completely missed the break statement. Can't mark my own comment as resolved.

**Comment by CoffeeFlux** [comment]
@monojenkins build failed

**Comment by CoffeeFlux** [comment]
@monojenkins build failed

File: mono/metadata/domain.c [hunk 2]
```diff
@@ -563,7 +562,7 @@ mono_init_internal (const char *filename, const char *exe_filename, const char *
 		 * that would mean it would be reloaded later. So instead, we save it to
 		 * exe_image, and close it during shutdown.
 		 */
-		get_runtimes_from_exe (exe_filename, &exe_image, runtimes);
+		runtimes = get_runtimes_from_exe (exe_filename, &exe_image, runtimes);
```
Comment (lambdageek) [inline mono/metadata/domain.c]: `runtimes` on the RHS here is always NULL, right?

File: mono/metadata/domain.c [hunk 3]
```diff
@@ -1888,26 +1888,26 @@ get_runtimes_from_exe (const char *file, MonoImage **out_image, const MonoRuntim
...
 			while (list != NULL) {
 				version = (char*) list->data;
 				runtime = get_runtime_by_version (version);
 				if (runtime != NULL)
-					runtimes [n++] = runtime;
+					runtimes = g_slist_prepend (runtimes, (gpointer)runtime);
 				list = g_slist_next (list);
 			}
-			runtimes [n] = NULL;
+			runtimes = g_slist_reverse (runtimes);
```
Comment (lambdageek) [inline mono/metadata/domain.c]: why?

also: `runtimes` starts out NULL when `get_runtimes_from_exe` is first called, right?  But if it wasn't - this would reverse the input portion of the list too, right?  That seems... undesirable.

Comment (CoffeeFlux) [reply mono/metadata/domain.c]: I wanted to preserve the order from the XML, and I believe prepending and then reversing is faster than appending a bunch of times. You're right about reversing the input portion, though I also agree that there's no reason for it to take an input runtimes at all, so I'm inclined to leave this once I fix that.

File: mono/metadata/domain.c (hunk 2 above)
Comment (CoffeeFlux) [reply mono/metadata/domain.c]: Yeah, no reason to pass it at all. Will change.

File: mono/metadata/domain.c (hunk 3 above)
Comment (lambdageek) [reply mono/metadata/domain.c]: Sounds good to me.

**Comment by CoffeeFlux** [comment]
@monojenkins build failed
