### PR TITLE
[mini] Add GC Unsafe transitions in mono_pmip

### LINKED ISSUE #21184: Crash in mono_pmip
## Steps to Reproduce

In VS Mac we use mono_pmip to symbolicate stack traces we get from objective c exceptions. The call to mono_pmip sometimes crashes. I don't have a reliable way to reproduce this in VSMac. I can make mono_pmip sometimes crash if I give it an incorrect address. If the address is correct, it seems to always work.

### Current Behavior

mono_pmip crashes sometimes.

### Expected Behavior

mono_pmip never crash. It should return null if the provided address is not valid.

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 6.12.0.147 (2020-02/35bf914659f Fri Jun 25 08:02:14 EDT 2021)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)

## Stacktrace

```
=================================================================
	Native stacktrace:
=================================================================
	0x10025b736 - /Users/lluis/prog/work/vsmac/master/vsmac/main/build/bin/VisualStudio.app/Contents/MacOS/VisualStudio : mono_dump_native_crash_info
	0x10024f38e - /Users/lluis/prog/work/vsmac/master/vsmac/main/build/bin/VisualStudio.app/Contents/MacOS/VisualStudio : mono_handle_native_crash
	0x10025ad5f - /Users/lluis/prog/work/vsmac/master/vsmac/main/build/bin/VisualStudio.app/Contents/MacOS/VisualStudio : sigabrt_signal_handler
	0x7fff205b9d7d - /usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x0 - Unknown
	0x7fff204c9411 - /usr/lib/system/libsystem_c.dylib : abort
	0x10016c4b0 - /Users/lluis/prog/work/vsmac/master/vsmac/main/build/bin/VisualStudio.app/Contents/MacOS/VisualStudio : _ZL12log_callbackPKcS0_S0_iPv
	0x10047c8d8 - /Users/lluis/prog/work/vsmac/master/vsmac/main/build/bin/VisualStudio.app/Contents/MacOS/VisualStudio : monoeg_g_logv_nofree
	0x10047c982 - /Users/lluis/prog/work/vsmac/master/vsmac/main/build/bin/VisualStudio.app/Contents/MacOS/VisualStudio : monoeg_g_log
	0x10046d83c - /Users/lluis/prog/work/vsmac/master/vsmac/main/build/bin/VisualStudio.app/Contents/MacOS/VisualStudio : mono_threads_transition_do_blocking
	0x10046b041 - /Users/lluis/prog/work/vsmac/master/vsmac/main/build/bin/VisualStudio.app/Contents/MacOS/VisualStudio : mono_threads_enter_gc_safe_region_unbalanced_with_info
	0x100318e58 - /Users/lluis/prog/work/vsmac/master/vsmac/main/build/bin/VisualStudio.app/Contents/MacOS/VisualStudio : mono_domain_lock
	0x10025ec8d - /Users/lluis/prog/work/vsmac/master/vsmac/main/build/bin/VisualStudio.app/Contents/MacOS/VisualStudio : mono_get_method_from_ip
	0x1316f8f13 - Unknown
	0x1316bf2eb - Unknown
	0x1316bd113 - Unknown
	0x128694ed3 - Unknown
	0x128694cb3 - Unknown
	0x128693fc7 - Unknown
	0x128693313 - Unknown
	0x11a233e4a - Unknown
	0x11995b9fe - Unknown
	0x11995b23b - Unknown
	0x11a05f04b - Unknown
	0x1199530ae - Unknown
	0x1199524cb - Unknown
	0x11995263b - Unknown
	0x100265fc3 - /Users/lluis/prog/work/vsmac/master/vsmac/main/build/bin/VisualStudio.app/Contents/MacOS/VisualStudio : mono_jit_runtime_invoke
	0x10039bdff - /Users/lluis/prog/work/vsmac/master/vsmac/main/build/bin/VisualStudio.app/Contents/MacOS/VisualStudio : mono_runtime_try_invoke
	0x1003e8f9a - /Users/lluis/prog/work/vsmac/master/vsmac/main/build/bin/VisualStudio.app/Contents/MacOS/VisualStudio : worker_callback
	0x1003e6bf1 - /Users/lluis/prog/work/vsmac/master/vsmac/main/build/bin/VisualStudio.app/Contents/MacOS/VisualStudio : worker_thread
	0x1003f2fb3 - /Users/lluis/prog/work/vsmac/master/vsmac/main/build/bin/VisualStudio.app/Contents/MacOS/VisualStudio : start_wrapper_internal
	0x1003f2dfe - /Users/lluis/prog/work/vsmac/master/vsmac/main/build/bin/VisualStudio.app/Contents/MacOS/VisualStudio : start_wrapper
	0x7fff205748fc - /usr/lib/system/libsystem_pthread.dylib : _pthread_start
	0x7fff20570443 - /usr/lib/system/libsystem_pthread.dylib : thread_start```

<!--
You can join us on Discord (https://aka.ms/dotnet-discord) in the #monovm channel to discuss your reported issue
-->

### PR DESCRIPTION
**Pull request by lambdageek**
Add a new mono_pmip_u that doesn't do the transition.

The intent is that Mono developers in the debugger can call still call
mono_pmip_u if the thread state machine is in a broken state.

Fixes #21184

### CODE REVIEW

File: mono/mini/mini-runtime.c [hunk 1]
```diff
@@ -213,6 +213,17 @@ find_tramp (gpointer key, gpointer value, gpointer user_data)
...
+	char *result;
+	MONO_ENTER_GC_UNSAFE;
+	result = mono_get_method_from_ip_u (ip);
+	MONO_EXIT_GC_UNSAFE;
+	return result;
+}
+
+/* debug function */
+char*
+mono_get_method_from_ip_u (void *ip)
```
Comment (vargaz) [inline mono/mini/mini-runtime.c:226]: Should be static.

**Review by vargaz — APPROVED** [review]

**Comment by lambdageek** [comment]
@monojenkins backport to 2020-02

**Comment by lambdageek** [comment]
@monojenkins build failed
