### PR TITLE
[metadata][dim] Unexpected System.NotSupportedException in presence of default interface implementations

### LINKED ISSUE #13401: Unexpected System.NotSupportedException in presence of default interface implementations
Several C# compiler tests are failing due to an unexpected System.NotSupportedException when compiled code is executed on Mono:
```
    Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.DefaultInterfaceImplementationTests.MethodImplementationInDerived_12 [FAIL]
      Roslyn.Test.Utilities.ExecutionException : 
      Execution failed for assembly '/opt/code/artifacts/tmp/Debug/RoslynTests'.
      Exception: System.NotSupportedException: Interface method 'I1:M1 ()' in class 'Test10' has multiple candidate implementations.
        at Test8.Main () [0x00021] in <b809b8ef942f4984a6cb0c1fc2ebbf5e>:0 
        at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
        at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <5c08ba3606524216b0550d239122568a>:0 
      ---- System.NotSupportedException : Interface method 'I1:M1 ()' in class 'Test10' has multiple candidate implementations.
      Stack Trace:
          at Roslyn.Test.Utilities.Desktop.DesktopRuntimeEnvironment.Execute (System.String moduleName, System.String[] args, System.String expectedOutput) [0x000ba] in <886db3940e124a9bbcbbdf03fe0d06f3>:0 
          at Microsoft.CodeAnalysis.Test.Utilities.CompilationVerifier.Emit (System.String expectedOutput, System.Nullable`1[T] expectedReturnCode, System.String[] args, System.Collections.Generic.IEnumerable`1[T] manifestResources, Microsoft.CodeAnalysis.Emit.EmitOptions emitOptions, Microsoft.CodeAnalysis.Test.Utilities.Verification peVerify, Microsoft.CodeAnalysis.Test.Utilities.SignatureDescription[] expectedSignatures) [0x00055] in <886db3940e124a9bbcbbdf03fe0d06f3>:0 
          at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit (Microsoft.CodeAnalysis.Compilation compilation, System.Collections.Generic.IEnumerable`1[T] dependencies, System.Collections.Generic.IEnumerable`1[T] manifestResources, Microsoft.CodeAnalysis.Test.Utilities.SignatureDescription[] expectedSignatures, System.String expectedOutput, System.Nullable`1[T] expectedReturnCode, System.String[] args, System.Action`1[T] assemblyValidator, System.Action`1[T] symbolValidator, Microsoft.CodeAnalysis.Emit.EmitOptions emitOptions, Microsoft.CodeAnalysis.Test.Utilities.Verification verify) [0x00016] in <886db3940e124a9bbcbbdf03fe0d06f3>:0 
          at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerifyCommon (Microsoft.CodeAnalysis.Compilation compilation, System.Collections.Generic.IEnumerable`1[T] manifestResources, System.Collections.Generic.IEnumerable`1[T] dependencies, System.Action`1[T] sourceSymbolValidator, System.Action`1[T] assemblyValidator, System.Action`1[T] symbolValidator, Microsoft.CodeAnalysis.Test.Utilities.SignatureDescription[] expectedSignatures, System.String expectedOutput, System.Nullable`1[T] expectedReturnCode, System.String[] args, Microsoft.CodeAnalysis.Emit.EmitOptions emitOptions, Microsoft.CodeAnalysis.Test.Utilities.Verification verify) [0x00074] in <886db3940e124a9bbcbbdf03fe0d06f3>:0 
          at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CompileAndVerify (Microsoft.CodeAnalysis.Compilation compilation, System.Collections.Generic.IEnumerable`1[T] manifestResources, System.Collections.Generic.IEnumerable`1[T] dependencies, System.Action`1[T] sourceSymbolValidator, System.Action`1[T] validator, System.Action`1[T] symbolValidator, Microsoft.CodeAnalysis.Test.Utilities.SignatureDescription[] expectedSignatures, System.String expectedOutput, System.Nullable`1[T] expectedReturnCode, System.String[] args, Microsoft.CodeAnalysis.Emit.EmitOptions emitOptions, Microsoft.CodeAnalysis.Test.Utilities.Verification verify) [0x00016] in <f691de03053643518f220434c02b8437>:0 
          at Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.DefaultInterfaceImplementationTests.MethodImplementationInDerived_12 () [0x00575] in <742c82f60cff4a969f1de442d7cb62c9>:0 
          at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
          at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <5c08ba3606524216b0550d239122568a>:0 
        ----- Inner Stack Trace -----
          at Test8.Main () [0x00021] in <b809b8ef942f4984a6cb0c1fc2ebbf5e>:0 
          at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
          at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <5c08ba3606524216b0550d239122568a>:0 
    Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.DefaultInterfaceImplementationTests.PropertyImplementationInDerived_12 [FAIL]
      Roslyn.Test.Utilities.ExecutionException : 
      Execution failed for assembly '/opt/code/artifacts/tmp/Debug/RoslynTests'.
      Exception: System.NotSupportedException: Interface method 'I1:get_M1 ()' in class 'Test10' has multiple candidate implementations.
        at Test8.Main () [0x0002d] in <61a5b54159c04079b2067a4bd6d43f27>:0 
        at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
        at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <5c08ba3606524216b0550d239122568a>:0 
      ---- System.NotSupportedException : Interface method 'I1:get_M1 ()' in class 'Test10' has multiple candidate implementations.
      Stack Trace:
          at Roslyn.Test.Utilities.Desktop.DesktopRuntimeEnvironment.Execute (System.String moduleName, System.String[] args, System.String expectedOutput) [0x000ba] in <886db3940e124a9bbcbbdf03fe0d06f3>:0 
          at Microsoft.CodeAnalysis.Test.Utilities.CompilationVerifier.Emit (System.String expectedOutput, System.Nullable`1[T] expectedReturnCode, System.String[] args, System.Collections.Generic.IEnumerable`1[T] manifestResources, Microsoft.CodeAnalysis.Emit.EmitOptions emitOptions, Microsoft.CodeAnalysis.Test.Utilities.Verification peVerify, Microsoft.CodeAnalysis.Test.Utilities.SignatureDescription[] expectedSignatures) [0x00055] in <886db3940e124a9bbcbbdf03fe0d06f3>:0 
          at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit (Microsoft.CodeAnalysis.Compilation compilation, System.Collections.Generic.IEnumerable`1[T] dependencies, System.Collections.Generic.IEnumerable`1[T] manifestResources, Microsoft.CodeAnalysis.Test.Utilities.SignatureDescription[] expectedSignatures, System.String expectedOutput, System.Nullable`1[T] expectedReturnCode, System.String[] args, System.Action`1[T] assemblyValidator, System.Action`1[T] symbolValidator, Microsoft.CodeAnalysis.Emit.EmitOptions emitOptions, Microsoft.CodeAnalysis.Test.Utilities.Verification verify) [0x00016] in <886db3940e124a9bbcbbdf03fe0d06f3>:0 
          at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerifyCommon (Microsoft.CodeAnalysis.Compilation compilation, System.Collections.Generic.IEnumerable`1[T] manifestResources, System.Collections.Generic.IEnumerable`1[T] dependencies, System.Action`1[T] sourceSymbolValidator, System.Action`1[T] assemblyValidator, System.Action`1[T] symbolValidator, Microsoft.CodeAnalysis.Test.Utilities.SignatureDescription[] expectedSignatures, System.String expectedOutput, System.Nullable`1[T] expectedReturnCode, System.String[] args, Microsoft.CodeAnalysis.Emit.EmitOptions emitOptions, Microsoft.CodeAnalysis.Test.Utilities.Verification verify) [0x00074] in <886db3940e124a9bbcbbdf03fe0d06f3>:0 
          at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CompileAndVerify (Microsoft.CodeAnalysis.Compilation compilation, System.Collections.Generic.IEnumerable`1[T] manifestResources, System.Collections.Generic.IEnumerable`1[T] dependencies, System.Action`1[T] sourceSymbolValidator, System.Action`1[T] validator, System.Action`1[T] symbolValidator, Microsoft.CodeAnalysis.Test.Utilities.SignatureDescription[] expectedSignatures, System.String expectedOutput, System.Nullable`1[T] expectedReturnCode, System.String[] args, Microsoft.CodeAnalysis.Emit.EmitOptions emitOptions, Microsoft.CodeAnalysis.Test.Utilities.Verification verify) [0x00016] in <f691de03053643518f220434c02b8437>:0 
          at Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.DefaultInterfaceImplementationTests.ValidatePropertyImplementationInDerived_12 (System.String source1, System.String source4, System.String source5, Microsoft.CodeAnalysis.Test.Utilities.DiagnosticDescription[] expected1, Microsoft.CodeAnalysis.Test.Utilities.DiagnosticDescription[] expected2) [0x003e5] in <742c82f60cff4a969f1de442d7cb62c9>:0 
          at Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.DefaultInterfaceImplementationTests.PropertyImplementationInDerived_12 () [0x001a4] in <742c82f60cff4a969f1de442d7cb62c9>:0 
          at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
          at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <5c08ba3606524216b0550d239122568a>:0 
        ----- Inner Stack Trace -----
          at Test8.Main () [0x0002d] in <61a5b54159c04079b2067a4bd6d43f27>:0 
          at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
          at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <5c08ba3606524216b0550d239122568a>:0 
    Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.DefaultInterfaceImplementationTests.IndexerImplementationInDerived_12 [FAIL]
      Roslyn.Test.Utilities.ExecutionException : 
      Execution failed for assembly '/opt/code/artifacts/tmp/Debug/RoslynTests'.
      Exception: System.NotSupportedException: Interface method 'I1:get_Item (int)' in class 'Test10' has multiple candidate implementations.
        at Test8.Main () [0x00031] in <9bb45cc53b034872a000df0b25588888>:0 
        at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
        at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <5c08ba3606524216b0550d239122568a>:0 
      ---- System.NotSupportedException : Interface method 'I1:get_Item (int)' in class 'Test10' has multiple candidate implementations.
      Stack Trace:
          at Roslyn.Test.Utilities.Desktop.DesktopRuntimeEnvironment.Execute (System.String moduleName, System.String[] args, System.String expectedOutput) [0x000ba] in <886db3940e124a9bbcbbdf03fe0d06f3>:0 
          at Microsoft.CodeAnalysis.Test.Utilities.CompilationVerifier.Emit (System.String expectedOutput, System.Nullable`1[T] expectedReturnCode, System.String[] args, System.Collections.Generic.IEnumerable`1[T] manifestResources, Microsoft.CodeAnalysis.Emit.EmitOptions emitOptions, Microsoft.CodeAnalysis.Test.Utilities.Verification peVerify, Microsoft.CodeAnalysis.Test.Utilities.SignatureDescription[] expectedSignatures) [0x00055] in <886db3940e124a9bbcbbdf03fe0d06f3>:0 
          at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit (Microsoft.CodeAnalysis.Compilation compilation, System.Collections.Generic.IEnumerable`1[T] dependencies, System.Collections.Generic.IEnumerable`1[T] manifestResources, Microsoft.CodeAnalysis.Test.Utilities.SignatureDescription[] expectedSignatures, System.String expectedOutput, System.Nullable`1[T] expectedReturnCode, System.String[] args, System.Action`1[T] assemblyValidator, System.Action`1[T] symbolValidator, Microsoft.CodeAnalysis.Emit.EmitOptions emitOptions, Microsoft.CodeAnalysis.Test.Utilities.Verification verify) [0x00016] in <886db3940e124a9bbcbbdf03fe0d06f3>:0 
          at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerifyCommon (Microsoft.CodeAnalysis.Compilation compilation, System.Collections.Generic.IEnumerable`1[T] manifestResources, System.Collections.Generic.IEnumerable`1[T] dependencies, System.Action`1[T] sourceSymbolValidator, System.Action`1[T] assemblyValidator, System.Action`1[T] symbolValidator, Microsoft.CodeAnalysis.Test.Utilities.SignatureDescription[] expectedSignatures, System.String expectedOutput, System.Nullable`1[T] expectedReturnCode, System.String[] args, Microsoft.CodeAnalysis.Emit.EmitOptions emitOptions, Microsoft.CodeAnalysis.Test.Utilities.Verification verify) [0x00074] in <886db3940e124a9bbcbbdf03fe0d06f3>:0 
          at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CompileAndVerify (Microsoft.CodeAnalysis.Compilation compilation, System.Collections.Generic.IEnumerable`1[T] manifestResources, System.Collections.Generic.IEnumerable`1[T] dependencies, System.Action`1[T] sourceSymbolValidator, System.Action`1[T] validator, System.Action`1[T] symbolValidator, Microsoft.CodeAnalysis.Test.Utilities.SignatureDescription[] expectedSignatures, System.String expectedOutput, System.Nullable`1[T] expectedReturnCode, System.String[] args, Microsoft.CodeAnalysis.Emit.EmitOptions emitOptions, Microsoft.CodeAnalysis.Test.Utilities.Verification verify) [0x00016] in <f691de03053643518f220434c02b8437>:0 
          at Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.DefaultInterfaceImplementationTests.ValidatePropertyImplementationInDerived_12 (System.String source1, System.String source4, System.String source5, Microsoft.CodeAnalysis.Test.Utilities.DiagnosticDescription[] expected1, Microsoft.CodeAnalysis.Test.Utilities.DiagnosticDescription[] expected2) [0x003e5] in <742c82f60cff4a969f1de442d7cb62c9>:0 
          at Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.DefaultInterfaceImplementationTests.IndexerImplementationInDerived_12 () [0x00332] in <742c82f60cff4a969f1de442d7cb62c9>:0 
          at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
          at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <5c08ba3606524216b0550d239122568a>:0 
        ----- Inner Stack Trace -----
          at Test8.Main () [0x00031] in <9bb45cc53b034872a000df0b25588888>:0 
          at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
          at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <5c08ba3606524216b0550d239122568a>:0 
    Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.DefaultInterfaceImplementationTests.EventImplementationInDerived_12 [FAIL]
      Roslyn.Test.Utilities.ExecutionException : 
      Execution failed for assembly ''.
      Exception: System.NotSupportedException: Interface method 'I1:add_M1 (System.Action)' in class 'Test10' has multiple candidate implementations.
        at Test8.Main () [0x00033] in <d11baf2080cd45679518d3afb1cc957a>:0 
        at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
        at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <5c08ba3606524216b0550d239122568a>:0 
      ---- System.NotSupportedException : Interface method 'I1:add_M1 (System.Action)' in class 'Test10' has multiple candidate implementations.
      Stack Trace:
          at Roslyn.Test.Utilities.Desktop.DesktopRuntimeEnvironment.Execute (System.String moduleName, System.String[] args, System.String expectedOutput) [0x000ba] in <886db3940e124a9bbcbbdf03fe0d06f3>:0 
          at Microsoft.CodeAnalysis.Test.Utilities.CompilationVerifier.Emit (System.String expectedOutput, System.Nullable`1[T] expectedReturnCode, System.String[] args, System.Collections.Generic.IEnumerable`1[T] manifestResources, Microsoft.CodeAnalysis.Emit.EmitOptions emitOptions, Microsoft.CodeAnalysis.Test.Utilities.Verification peVerify, Microsoft.CodeAnalysis.Test.Utilities.SignatureDescription[] expectedSignatures) [0x00055] in <886db3940e124a9bbcbbdf03fe0d06f3>:0 
          at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit (Microsoft.CodeAnalysis.Compilation compilation, System.Collections.Generic.IEnumerable`1[T] dependencies, System.Collections.Generic.IEnumerable`1[T] manifestResources, Microsoft.CodeAnalysis.Test.Utilities.SignatureDescription[] expectedSignatures, System.String expectedOutput, System.Nullable`1[T] expectedReturnCode, System.String[] args, System.Action`1[T] assemblyValidator, System.Action`1[T] symbolValidator, Microsoft.CodeAnalysis.Emit.EmitOptions emitOptions, Microsoft.CodeAnalysis.Test.Utilities.Verification verify) [0x00016] in <886db3940e124a9bbcbbdf03fe0d06f3>:0 
          at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerifyCommon (Microsoft.CodeAnalysis.Compilation compilation, System.Collections.Generic.IEnumerable`1[T] manifestResources, System.Collections.Generic.IEnumerable`1[T] dependencies, System.Action`1[T] sourceSymbolValidator, System.Action`1[T] assemblyValidator, System.Action`1[T] symbolValidator, Microsoft.CodeAnalysis.Test.Utilities.SignatureDescription[] expectedSignatures, System.String expectedOutput, System.Nullable`1[T] expectedReturnCode, System.String[] args, Microsoft.CodeAnalysis.Emit.EmitOptions emitOptions, Microsoft.CodeAnalysis.Test.Utilities.Verification verify) [0x00074] in <886db3940e124a9bbcbbdf03fe0d06f3>:0 
          at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CompileAndVerify (Microsoft.CodeAnalysis.Compilation compilation, System.Collections.Generic.IEnumerable`1[T] manifestResources, System.Collections.Generic.IEnumerable`1[T] dependencies, System.Action`1[T] sourceSymbolValidator, System.Action`1[T] validator, System.Action`1[T] symbolValidator, Microsoft.CodeAnalysis.Test.Utilities.SignatureDescription[] expectedSignatures, System.String expectedOutput, System.Nullable`1[T] expectedReturnCode, System.String[] args, Microsoft.CodeAnalysis.Emit.EmitOptions emitOptions, Microsoft.CodeAnalysis.Test.Utilities.Verification verify) [0x00016] in <f691de03053643518f220434c02b8437>:0 
          at Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.DefaultInterfaceImplementationTests.EventImplementationInDerived_12 () [0x0057b] in <742c82f60cff4a969f1de442d7cb62c9>:0 
          at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
          at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <5c08ba3606524216b0550d239122568a>:0 
        ----- Inner Stack Trace -----
          at Test8.Main () [0x00033] in <d11baf2080cd45679518d3afb1cc957a>:0 
          at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
          at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <5c08ba3606524216b0550d239122568a>:0 
```

Here is the gist of the scenario:
```
public interface I1
{
    void M1(){ System.Console.WriteLine(""Unexpected!!!""); } 
}

public interface I2 : I1
{
    void I1.M1() 
    {
        System.Console.WriteLine(""I2.I1.M1"");
    }
}

public interface I3 : I1
{
    void I1.M1() 
    {
        System.Console.WriteLine(""I3.I1.M1"");
    }
}

public interface I4 : I1
{
    void I1.M1() 
    {
        System.Console.WriteLine(""I4.I1.M1"");
    }
}

class Test10 : I1, I2, I3, I4
{
    public void M1() 
    {
        System.Console.WriteLine(""Test10.M1"");
    }
}
```

Runtime complains that: "Interface method 'I1:M1 ()' in class 'Test10' has multiple candidate implementations." However, this is incorrect, there is an implementation in the class, so implementations in interfaces shouldn't matter.

### PR DESCRIPTION
**Pull request by thaystg**
```
namespace Application
{
	public interface I1 { void M1() { System.Console.WriteLine("Unexpected!!!"); }}
	public interface I2 : I1 { void I1.M1() { System.Console.WriteLine("I2.I1.M1"); }}
	public interface I3 : I1 { void I1.M1() { System.Console.WriteLine("I3.I1.M1"); }}
	public interface I4 : I1 { void I1.M1() { System.Console.WriteLine("I4.I1.M1"); }}
	class Test10 : I1, I2, I3, I4 { public void M1() { System.Console.WriteLine("Test10.M1"); } }
	class MainClass {
		public static void Main(string[] args)
		{
			I1 var = new Test10();
			var.M1();
		}
	}
}
```

The interface method M1 is overridden at I1, at I2, at I3, at I4. The class Test10 overrides method M1 so regardless of having methods overridden in interface, the method of the class should be priority in this case. And then I remove the conflicts because there is not a conflict anymore.

Fixes #13401

### CODE REVIEW

**Comment by thaystg** [comment]
@monojenkins build failed

File: mono/metadata/class-init.c [hunk 1]
```diff
@@ -3151,60 +3151,58 @@ mono_class_setup_vtable_general (MonoClass *klass, MonoMethod **overrides, int o
...
+					TRACE_INTERFACE_VTABLE ((cm != NULL) && printf ("    For slot %d ('%s'.'%s':'%s'), trying (ancestor) method '%s'.'%s':'%s'... ", im_slot, ic->name_space, ic->name, im->name, cm->klass->name_space, cm->klass->name, cm->name));
+					if ((cm != NULL) && check_interface_method_override (klass, im, cm, FALSE, FALSE, TRUE)) {
+						TRACE_INTERFACE_VTABLE (printf ("[everything ok]: ASSIGNING"));
 						vtable [im_slot] = cm;
 						/* Why do we need this? */
 						if (cm->slot < 0) {
 							cm->slot = im_slot;
 						}
+						if (conflict_map)
+							g_hash_table_remove(conflict_map, im);
```
Comment (lambdageek) [inline mono/metadata/class-init.c]: I'm not sure about this one.

```csharp

interface I1 { void M1 () { Console.WriteLine ("M1"); }
interface I2 : I1 { void I1.M1 () { Console.WriteLine ("M2"); }

class C1 : I1 { public void M1 ()  { Console.WriteLine ("C1"); } // this one is okay; call to M1 will print C1

class C2 : C1 { } // this should be ok.  call to M1 will print C1

class C3 : C1, I2 { } // is this okay?   Will it print C1 or I2?

File: mono/metadata/class-init.c [hunk 2]
```diff
@@ -3151,60 +3151,58 @@ mono_class_setup_vtable_general (MonoClass *klass, MonoMethod **overrides, int o
...
-						TRACE_INTERFACE_VTABLE (printf ("    Using default iface method %s.\n", mono_method_full_name (im, 1)));
-						vtable [im_slot] = im;
-					}
+			if (vtable [im_slot] == NULL) {
+				if (!(im->flags & METHOD_ATTRIBUTE_ABSTRACT)) {
+					TRACE_INTERFACE_VTABLE (printf ("    Using default iface method %s.\n", mono_method_full_name (im, 1)));
+					vtable [im_slot] = im;
 				}
-			} else {
-				g_assert (vtable [im_slot] == override_im);
```
Comment (lambdageek) [inline mono/metadata/class-init.c]: Is there anything we can still assert at the end?  for example: either we found an override in the class (or its parent) itself or else the vtable slot is equal to the override_im?

File: mono/metadata/class-init.c (hunk 1 above)
Comment (thaystg) [reply mono/metadata/class-init.c]: It wil print C1 calling M1 from C2 and from C3. Using mono or coreclr.

File: mono/metadata/class-init.c (hunk 2 above)
Comment (thaystg) [reply mono/metadata/class-init.c]: Yes, I can check if the vtable[im_slot] is equal cm that is the override in the class(or its parent) or is equal to override_im.

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
@monojenkins build failed

File: mono/metadata/class-init.c (hunk 2 above)
Comment (thaystg) [reply mono/metadata/class-init.c]: Yes. Done.

File: mono/tests/dim-implements-multiple-interfaces.il [hunk 3]
```diff
@@ -0,0 +1,196 @@
...
+	.maxstack 1
+	.locals init (
+		class Application.I1	V_0)
+	IL_0000:  nop 
+	IL_0001:  newobj instance void class Application.Test10::'.ctor'()
+	IL_0006:  stloc.0 
+	IL_0007:  ldloc.0 
+	IL_0008:  callvirt instance void class Application.I1::M1()
+	IL_000d:  nop 
+	IL_000e:  ret
```
Comment (lambdageek) [inline mono/tests/dim-implements-multiple-interfaces.il]: @thaystg I think we should improve the test.  Right now all that we're testing is that Mono doesn't crash when one of these DIM methods is called.

We should change the test so that we're verifying that the _expected_ method is being called.
One way to do that is to change all the implementations of `I1.M1`  that we don't want to run to throw an exception.  That way mono will exit with a non-zero exit code if they ever get called.

Also there's a merge conflict that needs to be resolved.

Comment (thaystg) [reply mono/tests/dim-implements-multiple-interfaces.il]: Done!

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
@monojenkins build failed
