### PR TITLE
[jit] Align float/double Nan/Inf to uint conversion behavior with CoreCLR/LLVM/Roslyn

### LINKED ISSUE #14931: [netcore] Make System.Linq.Expressions.Tests.ConvertTests.ConvertFloatToUIntTest Pass
The test currently fails with:

```
System.Linq.Expressions.Tests.ConvertTests.ConvertFloatToUIntTest(useInterpreter: True) [FAIL]
      Assert.Equal() Failure
      Expected: 2147483648
      Actual:   0
      Stack Trace:
           at System.Linq.Expressions.Tests.ConvertTests.VerifyFloatToUInt(Single value, Boolean useInterpreter)
           at System.Linq.Expressions.Tests.ConvertTests.ConvertFloatToUIntTest(Boolean useInterpreter)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Determine why and make the test pass.

### LINKED ISSUE #14932: [netcore] Make System.Linq.Expressions.Tests.ConvertTests.ConvertNullableFloatToUIntTest Pass
The failure is the same as the one in https://github.com/mono/mono/issues/14931.

Only reason this issue exists is to track individual failures.

### LINKED ISSUE #14942: [netcore] Make System.Linq.Expressions.Tests.ConvertTests.ConvertNullableFloatToNullableUIntTest Pass
Fails w/ same stack trace as https://github.com/mono/mono/issues/14931.

Only reason this issue exists is to track individual failures.

### LINKED ISSUE #14943: [netcore] Make System.Linq.Expressions.Tests.ConvertTests.ConvertFloatToNullableUIntTest Pass
Fails w/ same stack trace as #14931.

Only reason this issue exists is to track individual failures.

### PR DESCRIPTION
**Pull request by filipnavara**
Fixes #14931
Fixes #14932
Fixes #14942
Fixes #14943

The conversions for `unchecked((ushort)double.NaN)` and `unchecked((byte)double.NaN)` produce zero. This aligns the behaviour for `unchecked((uint)double.NaN)` and `unchecked((ulong)double.NaN)` to also produce zero. This is important because the C# compiler does constant folding and the results for `return unchecked((uint)double.NaN)` and `var a = double.NaB; return unchecked((uint)a)` would be different.

For cross-reference, [the CoreCLR code](https://github.com/dotnet/coreclr/blob/ef7767a3ba1c0a34b55cbd5496b799b17218ca14/src/jit/codegenxarch.cpp#L6833-L6881) on x64 always generates 64-bit conversion instruction for float -> unsigned type conversion. This ensures that the exceptional NaN value (0x8000_0000_0000_0000) gets truncated to zero for data type smaller than 64 bits. The conversion to `ulong` is handled by a [helper call](https://github.com/dotnet/coreclr/blob/9bd2787a9dd2aa4d2b7d4f72afebc3dbe896e896/src/vm/jithelpers.cpp#L597-L612), just like in Mono.

Re-opening of #15871 (GitHub screwed up and stopped running new builds and then complained re-opening of PR is impossible because of forced push).

### CODE REVIEW

File: mono/metadata/jit-icall-reg.h [hunk 1]
```diff
@@ -116,6 +116,7 @@ MONO_JIT_ICALL (__emul_rconv_to_i8) \
 MONO_JIT_ICALL (__emul_rconv_to_ovf_i8) \
 MONO_JIT_ICALL (__emul_rconv_to_ovf_u8) \
 MONO_JIT_ICALL (__emul_rconv_to_ovf_u8_un) \
+MONO_JIT_ICALL (__emul_rconv_to_u4)	\
 MONO_JIT_ICALL (__emul_rconv_to_u8) \
```
Comment (vargaz) [inline mono/metadata/jit-icall-reg.h]: Need to bump the aot file format version in aot-runtime.h.

Comment (filipnavara) [reply mono/metadata/jit-icall-reg.h]: Good point!

**Comment by filipnavara** [comment]
Keeping it as draft until the CI goes green.
