### PR TITLE
[debugger] Remove assert when the DebuggerTypeProxy cannot be instantiated

### LINKED ISSUE #19492: Debugger crash when inspecting element
## Steps to Reproduce

1. Compile repro code with symbols and including a reference to the System.Runtime.CompilerServices.Unsafe.dll. I used: `csc.bat /unsafe Program.cs -r:C:\<Path to my project dir>\System.Runtime.CompilerServices.Unsafe.dll -debug:portable`
    - Note: If I used full debug symbols I hit an assert: `* Assertion: should not be reached at ..\mono\metadata\marshal-ilgen.c:6205`
2. Run repro executable: `"C:\Program Files\Mono\bin\mono.exe" --debug --debugger-agent=transport=dt_socket,embedding=1,server=y,suspend=n,address=127.0.0.1:50000 Program.exe`
3. Reproducible with both Rider and VS. Attach to process, Put a breakpoint on 2nd Console.ReadKey(); Hit enter in process window to trigger breakpoint.
4. Inspect access->MyAccessor
5. Observe crash: ``* Assertion at ..\mono\mini\debugger-agent.c:6490, condition `is_ok (error)' not met, function:do_invoke_method, Invalid generic instantiation assembly:<path to exe> type:FiskDebugView`1 member:(null)``

```C#
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace DebuggerCrash
{
    unsafe struct Blah
    {
        public void* Ptr;
    }
    [DebuggerTypeProxy(typeof(FiskDebugView<>))]
    unsafe struct Fisk<T> where T : unmanaged
    {
        public T* Ptr;
    }
    unsafe struct Accessor
    {
        public Blah blah;
        public ref Fisk<GCHandle> MyAccessor
        {
            get
            {
                fixed (void* ptr = &blah)
                {
                    return ref System.Runtime.CompilerServices.Unsafe.AsRef<Fisk<GCHandle>>(ptr);
                }
            }
        }
    }
    internal sealed class FiskDebugView<T> where T : unmanaged, IEquatable<T>
    {
        Fisk<T> Data;
        public FiskDebugView(Fisk<T> data)
        {
            Data = data;
        }
        public unsafe T[] Items
        {
            get
            {
                T[] result = new T[1];
                result[0] = Data.Ptr[0];
                return result;
            }
        }
    }
    class Program
    {
        public unsafe Program()
        {
            GCHandle test = default;
            var access = new Accessor { blah = new Blah { Ptr = &test } };
            Console.WriteLine((IntPtr)access.MyAccessor.Ptr);
            Console.ReadKey();
            Console.ReadKey();
        }

        static void Main(string[] args)
        {
            new Program();
        }
    }
}
```

### Current Behavior
Crashes with:
``* Assertion at ..\mono\mini\debugger-agent.c:6490, condition `is_ok (error)' not met, function:do_invoke_method, Invalid generic instantiation assembly:<path to exe> type:FiskDebugView`1 member:(null)``

### Expected Behavior
No crash - looks like there are different constraints between production code and proxy?

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[X] Windows

**Version Used**:

```
Mono JIT compiler version 6.8.0 (Visual Studio built mono)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notification:  Thread + polling
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       preemptive
        GC:            sgen (concurrent by default)
```

## Stacktrace

```
Let me know if you need a stacktrace. I can grab one with the latest master branch if need be.
```

### PR DESCRIPTION
**Pull request by thaystg**
Remove the assert because we don't need to stop the debug if we cannot create the object when calling the constructor using invoke_method, if it's a DebuggerTypeProxy, we are not able to show the value of the DebuggerTypeProxy, but we still can show the Raw View, if it's not the case of DebuggerTypeProxy, we just cannot evaluate this expression, but we can continue the debug session.

Fix #19492

### CODE REVIEW

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
@monojenkins backport 2020-02

File: mono/mini/debugger-agent.c [hunk 1]
```diff
@@ -6549,7 +6549,8 @@ do_invoke_method (DebuggerTlsData *tls, Buffer *buf, InvokeData *invoke, guint8
 			else {
 				ERROR_DECL (error);
 				this_arg = mono_object_new_checked (domain, m->klass, error);
-				mono_error_assert_ok (error);
+				if (!is_ok (error))
+					return ERR_INVALID_ARGUMENT;
```
Comment (lambdageek) [inline mono/mini/debugger-agent.c:6553]: This should have been 
```
				if (!is_ok (error)) {
					mono_error_cleanup (error);
					return ERR_INVALID_ARGUMENT;
				}
```

Comment (jaykrell) [reply mono/mini/debugger-agent.c:6553]: Single point of return, at least while not C++?
