### PR TITLE
Transactionscope timeout

### LINKED ISSUE #19955: TransactionScope ignores timeout
We've been having an issue where TransactionScope does not time out therefore not triggering the expected Rollback of the Transaction. There was a bug report in bugzilla claiming it was fixed, but it seems to persist https://xamarin.github.io/bugzilla-archives/31/31197/bug.html

## Steps to Reproduce

There is an even simpler repro code from the one in the linked bug:

```cs
static void Main(string[] args)
{
	try
	{
		using (var ts = new TransactionScope(TransactionScopeOption.Required,
			TimeSpan.FromSeconds(1)))
		{
			System.Threading.Thread.Sleep(2000);
			ts.Complete();
		}

		Console.WriteLine("Finished");
	}
	catch(Exception e)
	{
		Console.WriteLine(e.Message);
	}
}
```

### Current Behavior

The code outputs "Finished" and successfully completes the transaction scope.

### Expected Behavior

This should output "The transaction has aborted." and Rollback the transaction.

## On which platforms did you notice this

[X] macOS
[X] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 6.8.0.96 (tarball Wed Jan 15 10:18:35 UTC 2020)

### PR DESCRIPTION
**Pull request by poloBBQ**
Fixes #19955

### CODE REVIEW

File: mcs/class/System.Transactions/System.Transactions/Transaction.cs [hunk 1]
```diff
@@ -92,7 +96,29 @@ internal Transaction (Transaction other)
...
+		internal event TransactionCompletedEventHandler TransactionCompletedInternal;
+
+		// Transaction B was cloned from transaction A. Add event handlers to A
+		// when they are added to B. This will not work when new handlers are added to A
+		// as A has no reference to B.
+		public event TransactionCompletedEventHandler TransactionCompleted
+		{
+			add
+			{
+				if(this.internalTransaction != null)
```
Comment (akoeplinger) [inline mcs/class/System.Transactions/System.Transactions/Transaction.cs:108]:
```suggestion
				if (this.internalTransaction != null)
```

File: mcs/class/System.Transactions/System.Transactions/Transaction.cs [hunk 2]
```diff
@@ -92,7 +96,29 @@ internal Transaction (Transaction other)
...
+					this.internalTransaction.TransactionCompleted += value;
+
+				TransactionCompletedInternal += value;
+			}
+
+			remove
+			{
+				if(this.internalTransaction != null)
```
Comment (akoeplinger) [inline mcs/class/System.Transactions/System.Transactions/Transaction.cs:116]:
```suggestion
				if (this.internalTransaction != null)
```

File: mcs/class/System.Transactions/System.Transactions/TransactionScope.cs [hunk 3]
```diff
@@ -143,8 +146,35 @@ public TransactionScope(TransactionScopeOption option, TransactionScopeAsyncFlow
 				transaction.InitScope (this);
 			if (parentScope != null)
 				parentScope.nested ++;
+			if(timeout != TimeSpan.Zero)
+				scopeTimer = new Timer(TransactionScope.TimerCallback, this, scopeTimeout, TimeSpan.Zero);
```
Comment (akoeplinger) [inline mcs/class/System.Transactions/System.Transactions/TransactionScope.cs:150]:
```suggestion
			if (timeout != TimeSpan.Zero)
				scopeTimer = new Timer (TransactionScope.TimerCallback, this, scopeTimeout, TimeSpan.Zero);
```

File: mcs/class/System.Transactions/System.Transactions/TransactionScope.cs [hunk 4]
```diff
@@ -143,8 +146,35 @@ public TransactionScope(TransactionScopeOption option, TransactionScopeAsyncFlow
...
+			{
+				try
+				{
+					this.transaction.Rollback();
+					this.aborted = true;
+				}
+				catch ( ObjectDisposedException ex ) { }
+				catch ( TransactionException txEx ) { }
+			}
+ 		}
```
Comment (akoeplinger) [inline mcs/class/System.Transactions/System.Transactions/TransactionScope.cs:176]:
```suggestion
		private static void TimerCallback (object state)
		{
			TransactionScope scope = state as TransactionScope;
			if (null == scope)
			{
				throw new TransactionException ("TransactionScopeTimerObjectInvalid", null);
			}

			scope.TimeoutScope ();
		}

		private void TimeoutScope()
		{
			if (!completed && transaction != null)
			{
				try
				{
					this.transaction.Rollback ();
					this.aborted = true;
				}
				catch (ObjectDisposedException ex) { }
				catch (TransactionException txEx) { }
			}
 		}
```

File: mcs/class/System.Transactions/Test/TransactionScopeTest.cs [hunk 5]
```diff
@@ -1114,6 +1114,18 @@ public void ExplicitIsolationLevel()
...
 		}
+
+		[Test]
+		[ExpectedException(typeof(TransactionAbortedException))]
+		public void TransactionScopeTimeout()
+		{
+			Assert.IsNull(Transaction.Current, "Ambient transaction exists (before)");
+			using (var ts = new TransactionScope(TransactionScopeOption.Required, TimeSpan.FromMilliseconds(1)))
+			{
+				for(int i = 0; i < 1000000000; i += 2) i--;
```
Comment (akoeplinger) [inline mcs/class/System.Transactions/Test/TransactionScopeTest.cs:1125]: I don't understand what this loop does?

Comment (poloBBQ) [reply mcs/class/System.Transactions/Test/TransactionScopeTest.cs:1125]: I was trying to do a loop that would take longer than the specified timeout.

The obvious way would have been referencing System.Threading and sleeping the thread instead of looping. I tried looking at the tests structure but couldn't understand what I should do to reference the Thread class, any help there is greatly appreciated :)

Comment (akoeplinger) [reply mcs/class/System.Transactions/Test/TransactionScopeTest.cs:1125]: @poloBBQ adding `using System.Threading;` to the top of the file should be enough. Let me know if you run into issues :)

Comment (poloBBQ) [reply mcs/class/System.Transactions/Test/TransactionScopeTest.cs]: You're right, I was trying to use the namespace explicitly (i.e. System.Threading.Thread.Sleep(...)) and was getting an error when running the tests
`error CS0234: The type or namespace name 'Threading' does not exist in the namespace 'MonoTests.System' (are you missing an assembly reference?)`

Much better like this!

I think all your suggestions are accepted and this change committed properly, not sure everything is right as this is the first PR review I receive.

**Comment by akoeplinger** [comment]
@monojenkins build

File: mcs/class/System.Transactions/Test/TransactionScopeTest.cs (hunk 5 above)
Comment (akoeplinger) [reply mcs/class/System.Transactions/Test/TransactionScopeTest.cs]: Looks good, thanks

**Comment by akoeplinger** [comment]
Thank you for the contribution!
