### PR TITLE
Partially exclude custom modifiers from metadata type equality

### LINKED ISSUE #10945: Serialization error in nightly build
## Steps to Reproduce
This was found attempting to get the C# semantic tests running on Mono

1. Clone https://github.com/jaredpar/roslyn
1. Check out the branch `repro/mono-serialize`
1. Make sure mono is on your path
1. Run `./build.sh --restore --build`
1. Run `./build/scripts/test.sh Debug mono Microsoft.CodeAnalysis.CSharp.Symbo` 

### Actual Behavior
This will run the Symbol unit tests only and eventually Mono will throw an exception trying to call `ITestCase.Traits` across `AppDomain` instances. The error is a `NullReferenceException` during serialization 

### Expected Behavior
The xunit process runs to completion 

## On which platforms did you notice this

This was discovered on Ubuntu 18.04. I'm using the latest nightly mono as described by the Download page

https://www.mono-project.com/download/nightly/#download-lin

```
Mono JIT compiler version 5.19.0.290 (tarball Tue Sep  4 10:59:48 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(4)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

## Stacktrace and full details 

```
    [FATAL ERROR] System.NullReferenceException
      System.NullReferenceException : Object reference not set to an instance of an object
      Stack Trace:
        
        
        Server stack trace: 
          at System.Runtime.Serialization.FormatterServices.GetParentTypes (System.RuntimeType parentType, System.RuntimeType[]& parentTypes, System.Int32& parentTypeCount) [0x0001f] in <5a872f306a874e34bfe4796f739b7324>:0 
          at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers (System.RuntimeType type) [0x00089] in <5a872f306a874e34bfe4796f739b7324>:0 
          at System.Runtime.Serialization.FormatterServices+<>c__DisplayClass9_0.<GetSerializableMembers>b__0 (System.Runtime.Serialization.MemberHolder _) [0x00000] in <5a872f306a874e34bfe4796f739b7324>:0 
          at System.Collections.Concurrent.ConcurrentDictionary`2[TKey,TValue].GetOrAdd (TKey key, System.Func`2[T,TResult] valueFactory) [0x00034] in <5a872f306a874e34bfe4796f739b7324>:0 
          at System.Runtime.Serialization.FormatterServices.GetSerializableMembers (System.Type type, System.Runtime.Serialization.StreamingContext context) [0x0005e] in <5a872f306a874e34bfe4796f739b7324>:0 
          at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo () [0x0003d] in <5a872f306a874e34bfe4796f739b7324>:0 
          at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize (System.Object obj, System.Runtime.Serialization.ISurrogateSelector surrogateSelector, System.Runtime.Serialization.StreamingContext context, System.Runtime.Serialization.Formatters.Binary.SerObjectInfoInit serObjectInfoInit, System.Runtime.Serialization.IFormatterConverter converter, System.Runtime.Serialization.Formatters.Binary.ObjectWriter objectWriter, System.Runtime.Serialization.SerializationBinder binder) [0x00158] in <5a872f306a874e34bfe4796f739b7324>:0 
          at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.Serialize (System.Object obj, System.Runtime.Serialization.ISurrogateSelector surrogateSelector, System.Runtime.Serialization.StreamingContext context, System.Runtime.Serialization.Formatters.Binary.SerObjectInfoInit serObjectInfoInit, System.Runtime.Serialization.IFormatterConverter converter, System.Runtime.Serialization.Formatters.Binary.ObjectWriter objectWriter, System.Runtime.Serialization.SerializationBinder binder) [0x00006] in <5a872f306a874e34bfe4796f739b7324>:0 
          at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write (System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo objectInfo, System.Runtime.Serialization.Formatters.Binary.NameInfo memberNameInfo, System.Runtime.Serialization.Formatters.Binary.NameInfo typeNameInfo) [0x00101] in <5a872f306a874e34bfe4796f739b7324>:0 
          at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize (System.Object graph, System.Runtime.Remoting.Messaging.Header[] inHeaders, System.Runtime.Serialization.Formatters.Binary.__BinaryWriter serWriter, System.Boolean fCheck) [0x001d3] in <5a872f306a874e34bfe4796f739b7324>:0 
          at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize (System.IO.Stream serializationStream, System.Object graph, System.Runtime.Remoting.Messaging.Header[] headers, System.Boolean fCheck) [0x0006e] in <5a872f306a874e34bfe4796f739b7324>:0 
          at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize (System.IO.Stream serializationStream, System.Object graph, System.Runtime.Remoting.Messaging.Header[] headers) [0x00000] in <5a872f306a874e34bfe4796f739b7324>:0 
          at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize (System.IO.Stream serializationStream, System.Object graph) [0x00000] in <5a872f306a874e34bfe4796f739b7324>:0 
          at System.Runtime.Remoting.RemotingServices.SerializeCallData (System.Object obj) [0x00053] in <5a872f306a874e34bfe4796f739b7324>:0 
          at (wrapper xdomain-dispatch) Xunit.Sdk.TestMethodTestCase.get_Traits(object,byte[]&,byte[]&)
        
        Exception rethrown at [0]: 
          at (wrapper xdomain-invoke) Xunit.Sdk.TestMethodTestCase.get_Traits()
          at MessageSinkMessageExtensions.Dispatch[TMessage] (Xunit.Abstractions.IMessageSinkMessage message, System.Collections.Generic.HashSet`1[T] messageTypes, Xunit.MessageHandler`1[TMessage] callback) [0x0001a] in <7906e2ced2224c19a10a02057b1365de>:0 
          at (wrapper remoting-invoke-with-check) Xunit.MessageSinkAdapter.OnMessageWithTypes(Xunit.Abstractions.IMessageSinkMessage,System.Collections.Generic.HashSet`1<string>)
          at (wrapper xdomain-dispatch) Xunit.MessageSinkAdapter.OnMessageWithTypes(object,byte[]&,byte[]&)
        
        Exception rethrown at [1]: 
          at (wrapper xdomain-invoke) Xunit.MessageSinkAdapter.OnMessageWithTypes(Xunit.Abstractions.IMessageSinkMessage,System.Collections.Generic.HashSet`1<string>)

```

### PR DESCRIPTION
**Pull request by kg**
Fixes #10945
Reverts fix for #6936

https://github.com/mono/mono/issues/10945 appears to have been introduced by https://github.com/mono/mono/commit/9dc6c344ac34a470fa0f4fc411e357f7eaf577fd. Unfortunately it is not possible to revert the commit at this point using git revert, but manually disabling the equality change fixes BinaryFormatter. This should be sufficient to get a lot of the broken roslyn tests working again.

### CODE REVIEW

**Comment by lambdageek** [comment]
This is going to regress #6936

**Comment by marek-safar** [comment]
@kg could you undo the indentation for no line damage

**Comment by marek-safar** [comment]
@lambdageek we know but the change caused regression

**Comment by kg** [comment]
I'm attempting a new approach here where I disable the cmod equality check for types that aren't pointers, since this appears to keep roslyn tests from breaking while satisfying the test case that was breaking on CI. We should find out if this is a satisfactory workaround for #6936 until we can properly support cmods.

**Comment by kg** [comment]
@monojenkins build failed

**Comment by kg** [comment]
@OmarTawfik For your use cases will it be sufficient for mono to (temporarily) only check cmods on certain types? Our test case only uses pointers, but I saw your original bug report mentioned ```ref int```, so I'm wondering what scenarios we need to handle to avoid breaking your code.

**Comment by kg** [comment]
This is now mergeable with the caveat that it probably regresses behaviors that are not covered by the tests we currently run. I'm going to figure out what some of those are, but ultimately I don't think we can know without talking to the people using this feature.

**Comment by kg** [comment]
The testcase in monobug.zip from #6936 breaks with this change. If I alter the change to include byref types (since they're addresses) it fixes 6936 but breaks at least 8 roslyn test cases (however, the binaryformatter issue stays gone).

**Comment by kg** [comment]
@monojenkins build failed

File: mono/metadata/metadata.c [hunk 1]
```diff
@@ -5575,34 +5583,46 @@ do_mono_metadata_type_equal (MonoType *t1, MonoType *t2, gboolean signature_only
...
-		return mono_metadata_fnptr_equal (t1->data.method, t2->data.method, signature_only);
+		result = mono_metadata_fnptr_equal (t1->data.method, t2->data.method, signature_only);
+		break;
 	default:
 		g_error ("implement type compare for %0x!", t1->type);
 		return FALSE;
 	}
 
-	return FALSE;
+	if (cmod_reject && is_pointer)
```
Comment (jaykrell) [inline mono/metadata/metadata.c]: Why isn't this before the switch?

Comment (kg) [reply mono/metadata/metadata.c]: I was doing diagnostic checks before by comparing the result of the switch with the cmod check. This allows you to log which comparisons are failing.

**Comment by lambdageek** [comment]
@kg @marek-safar Why was this merged if it breaks #6936?
