### PR TITLE
Fix ordinal imports on Windows.

### LINKED ISSUE #21122: DllImport by ordinal does not work
## Steps to Reproduce

1. Compile test case:
```
using System;
using System.Runtime.InteropServices;

static class TestOrdinalImport
{
	[DllImport("shlwapi", EntryPoint="#33")]
	unsafe extern static bool IsCharDigitW(char ch);

    public static int Main()
    {
		if (!IsCharDigitW('2'))
			return 1;
		if (IsCharDigitW('s'))
			return 2;
		return 0;
    }
}
```
2. Run on a Windows build of Mono.

### Current Behavior

Fails with EntryPointNotFoundException

### Expected Behavior

Exits successfully.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[x] Windows

**Version Used**:

Mono JIT compiler version 6.12.0 (Visual Studio built mono)

## Stacktrace

```
Unhandled Exception:
System.EntryPointNotFoundException: #33 assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) TestOrdinalImport.IsCharDigitW(char)
  at TestOrdinalImport.Main () [0x00001] in <8a2d827641004700b33ccad83e37b6ce>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.EntryPointNotFoundException: #33 assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) TestOrdinalImport.IsCharDigitW(char)
  at TestOrdinalImport.Main () [0x00001] in <8a2d827641004700b33ccad83e37b6ce>:0
```

### PR DESCRIPTION
**Pull request by madewokherd**
Fixes #21122 

We have existing code for this, but as the test case shows, it doesn't work. It's not really clear how it's supposed to work, since all it does is skip the "#" in the entry point name. GetProcAddress does not interpret numeric strings as ordinals, but it will interpret a pointer address from 1 to 65535 as an ordinal.

### CODE REVIEW

File: mono/metadata/native-library.c [hunk 1]
```diff
@@ -1456,16 +1456,6 @@ pinvoke_probe_for_symbol (MonoDl *module, MonoMethodPInvoke *piinfo, const char
 
 	g_assert (error_msg_out);
 
-#ifdef HOST_WIN32
-	if (import && import [0] == '#' && isdigit (import [1])) {
```
Comment (lateralusX) [inline mono/metadata/native-library.c:1460]: I believe the intent was probably to check if its an ordinal and then use the string version of the ordinal in the import, but that would never work due to how GetProcAddress lpProcName parameter works:

`The function or variable name, or the function's ordinal value. If this parameter is an ordinal value, it must be in the low-order word; the high-order word must be zero.`

File: mono/utils/mono-dl-windows.c [hunk 2]
```diff
@@ -157,7 +157,21 @@ mono_dl_lookup_symbol (MonoDl *module, const char *symbol_name)
 
 	/* get the symbol directly from the specified module */
 	if (!module->main_module)
+	{
```
Comment (lateralusX) [inline mono/utils/mono-dl-windows.c:160]: Should we only do this for none main module or should we add same capabilities to lookup by ordinal in main module as well?

**Review by lateralusX — APPROVED** [review]
Just a minor comment, LGTM, thanks for fixing this!

File: mono/utils/mono-dl-windows.c (hunk 2 above)
Comment (madewokherd) [reply mono/utils/mono-dl-windows.c:160]: Well, "__Internal" is a Mono-only feature, right? So doing that wouldn't add compatibility with .NET Framework. I'm not sure there's any other reason to add this. If we did, we'd only want to search the main exe and not every loaded module, because collisions are likely.

Comment (lateralusX) [reply mono/utils/mono-dl-windows.c:160]: It will look in the main binary (the .exe) in case main_module is true, so its more a mono feature and not something you use in C# dllimport's, but since this is generic library code used from within runtime, I don't see why we should restrict this use case compared to cases when you just use a symbol name.

Comment (madewokherd) [reply mono/utils/mono-dl-windows.c:160]: What are the possible use cases for this? Either you want to use an export from the mono runtime itself (in which case the export should have a name anyway, using it this way would be less portable, and the ordinal is probably inconsistent as exports change), or you are embedding Mono in a mixed-mode or native exe that has ordinal exports. I guess I could see an argument for this in the unlikely case that the runtime is embedded using a generic plugin API that expects plugins to do this, but in that case we should search only the main exe so we don't get collisions making things inconsistent.

Comment (lateralusX) [reply mono/utils/mono-dl-windows.c:160]: Thoughts was more that its a low level method in utils lib and the old implementation (that didn't do the right thing) seemed to have the intent to run it through all paths of mono_dl_lookup_symbol even in this case of ordinal, but didn't work due to incorrect implementation.

Ordinal exports should normally keep their numbers, or it will break clients.

I agree that the fallback looking through all loaded modules is incorrect and not something you would do because you will have no idea what you will get back.

But since ordinals is an edge case apparently not working at all in the past, I'm fine with just looking at the current module.

**Comment by lambdageek** [comment]
@monojenkins build
