### PR TITLE
Include pseudo custom attributes to CustomAttributes property

### LINKED ISSUE #7615: Custom MarshalAs attributes are not included in ParameterInfo objects retrieved via reflection
## Steps to Reproduce

1. Create a method with an attribute decorated with the `MarshalAs` attribute.
2. Use reflection to retrieve a `MethodInfo` instance, and then a `ParameterInfo` instance corresponding to the attribute.
3. Inspect the `CustomAttributes` property.
4. Observe that the `MarshalAs` attribute is not included in the collection.

-- alternatively --

1. Compile the [provided minimal test case][1] using `csc Program.cs` (substituting `Program.cs` for the filename you saved the source as)
3. Execute the test case using `mono Program.exe` (substituting `Program.exe` for the output filename)
2. Observe the output of the application. You should see an output similar to the following:

```
Custom attribute count: 0
Running on Mono.
Type of value in internal field: MarshalAsAttribute
```

## Current Behavior
In the current development version of Mono, `MarshalAs` attributes are not included in the collection assigned to `CustomAttributes`  property. Instead, they are present as an instance of the attribute, assigned to a private field (`marshalAs`).

## Expected Behavior
The `MarshalAs` attribute should be included in the collection assigned to the `CustomAttributes` property, as is the behaviour on the .NET Framework and .NET Core.

### On which platforms did you notice this

-[ ] macOS
-[x] Linux ([System Information][2])
-[ ] Windows

**Version Used**:
```
Mono JIT compiler version 5.10.0.170 (tarball Sat Mar 10 09:49:08 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)

```

[1]: https://hastebin.com/subovodode.cs
[2]: https://gist.github.com/400659620841d3e1a96b792e52b00841

### PR DESCRIPTION
**Pull request by MaximLipnin**
Fixes #7615

### CODE REVIEW

**Comment by MaximLipnin** [comment]
@marek-safar Could you please take a look?

File: mcs/class/corlib/System/MonoCustomAttrs.cs [hunk 1]
```diff
@@ -295,13 +295,104 @@ internal static object[] GetCustomAttributes (ICustomAttributeProvider obj, bool
...
+			throw new NotImplementedException ();
+		}
+
+		internal static IList<CustomAttributeData> GetCustomAttributesDataBase (ICustomAttributeProvider obj, Type attributeType, bool inheritedOnly)
+		{
+			CustomAttributeData[] attrsData;
+			if (IsUserCattrProvider (obj)) {
+				//FIXME resolve this case if it makes sense. Assign empty array for now.
+				//attrsData = obj.GetCustomAttributesData(attributeType, true);
+				attrsData = new CustomAttributeData [0];
```
Comment (marek-safar) [inline mcs/class/corlib/System/MonoCustomAttrs.cs]: Should be Array.Empty

File: mcs/class/corlib/System/MonoCustomAttrs.cs [hunk 2]
```diff
@@ -295,13 +295,104 @@ internal static object[] GetCustomAttributes (ICustomAttributeProvider obj, bool
...
+				attrsData = GetCustomAttributesDataInternal (obj);
+
+			//
+			// All pseudo custom attributes are Inherited = false hence we can avoid
+			// building attributes data array which would be discarded by inherited checks
+			//
+			if (!inheritedOnly) {
+				CustomAttributeData[] pseudoAttrsData = GetPseudoCustomAttributesData (obj, attributeType);
+				if (pseudoAttrsData != null) {
+					CustomAttributeData[] res = new CustomAttributeData [attrsData.Length + pseudoAttrsData.Length];
```
Comment (marek-safar) [inline mcs/class/corlib/System/MonoCustomAttrs.cs]: You could optimize for `attrsData.Length == 0`

File: mcs/class/corlib/System.Reflection/CustomAttributeData.cs [hunk 3]
```diff
@@ -64,6 +64,15 @@ internal CustomAttributeData (ConstructorInfo ctorInfo, Assembly assembly, IntPt
 			this.lazyData.data_length = data_length;
 		}
 
+		internal static CustomAttributeData Create (ConstructorInfo ctorInfo, IList<CustomAttributeTypedArgument> ctorArgs, IList<CustomAttributeNamedArgument> namedArgs)
```
Comment (marek-safar) [inline mcs/class/corlib/System.Reflection/CustomAttributeData.cs]: Instead of factory just add this as ctor overload

File: mcs/class/corlib/System.Reflection/FieldInfo.cs [hunk 4]
```diff
@@ -222,6 +223,55 @@ internal object[] GetPseudoCustomAttributes ()
...
+			if (marshalAs != null)
+				count++;
+
+			if (count == 0)
+				return null;
+			CustomAttributeData[] attrsData = new CustomAttributeData [count];
+			count = 0;
+
+			if (IsNotSerialized)
+				attrsData [count++] = CustomAttributeData.Create (
```
Comment (marek-safar) [inline mcs/class/corlib/System.Reflection/FieldInfo.cs]: Add ctor overload with `ConstructorInfo ctorInfo` only instead of passing extra 2 empty arguments at many places

File: mcs/class/corlib/System.Reflection/FieldInfo.cs [hunk 5]
```diff
@@ -222,6 +223,55 @@ internal object[] GetPseudoCustomAttributes ()
...
+					(typeof (NonSerializedAttribute)).GetConstructor (Type.EmptyTypes),
+					EmptyArray<CustomAttributeTypedArgument>.Value,
+					EmptyArray<CustomAttributeNamedArgument>.Value);
+			if (DeclaringType.IsExplicitLayout) {
+				var ctorArgs = new List<CustomAttributeTypedArgument> (
```
Comment (marek-safar) [inline mcs/class/corlib/System.Reflection/FieldInfo.cs]: Should new an array instead of List<T>

(repeated at many places)

File: mcs/class/corlib/System/MonoCustomAttrs.cs [hunk 6]
```diff
@@ -295,13 +295,104 @@ internal static object[] GetCustomAttributes (ICustomAttributeProvider obj, bool
...
-				throw new ArgumentNullException ("obj");
+				throw new ArgumentNullException (nameof (obj));
+
+			if (!inherit)
+				return GetCustomAttributesDataBase (obj, null, false);
+
+			return GetCustomAttributesData (obj, typeof (MonoCustomAttrs), inherit);
+		}
+
+		private static IList<CustomAttributeData> GetCustomAttributesData (ICustomAttributeProvider obj, Type type, bool inherit)
```
Comment (marek-safar) [inline mcs/class/corlib/System/MonoCustomAttrs.cs]: Not sure we need extra method to throw NIE just inline the throw

**Comment by MaximLipnin** [comment]
@marek-safar Thanks for review!
