### PR TITLE
[tools]: Use the official 'SslStream' APIs in certmgr.

### LINKED ISSUE #8421: certmgr --ssl https://community.letsencrypt.org hangs forever
## Steps to Reproduce

1. certmgr --ssl https://community.letsencrypt.org

Output:
```
Mono Certificate Manager - version 5.8.1.0
Manage X.509 certificates and CRL from stores.
Copyright 2002, 2003 Motus Technologies. Copyright 2004-2008 Novell. BSD licensed.
```
... and this hangs there forever.

## Current Behavior

Using mono 5.8.1 on OSX, and trying to load/access some https-enabled websites fails never returning back.

## Expected Behavior

Normal access to intended HTTPS site.

### On which platforms did you notice this

[x] macOS
[x] Linux
[ ] Windows

**Version Used**:

OSX:
```
Mono JIT compiler version 5.8.1.0 (2017-10/6bf3922f3fd Thu Mar  8 17:00:31 EST 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           normal
        SIGSEGV:       altstack
        Notification:  kqueue
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          yes(3.6.0svn-mono-master/8b1520c8aae)
        GC:            sgen (concurrent by default)
```

Linux (has btls enabled):
```
Mono JIT compiler version 4.8.1 (Stable 4.8.1.0/22a39d7 Sun Jul  2 06:45:50 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	LLVM:          supported, not enabled.
	GC:            sgen
```

### Stacktrace

N/A

### PR DESCRIPTION
**Pull request by baulig**
Fixes #8421.

### CODE REVIEW

File: mcs/tools/security/certmgr.cs [hunk 1]
```diff
@@ -447,36 +447,22 @@ static X509CertificateCollection GetCertificatesFromSslSession (string url)
...
-			if (pi == null) {
-				Console.WriteLine ("Sorry but you need a newer version of Mono.Security.dll to use this feature.");
-				return null;
-			}
-			return (X509CertificateCollection) pi.GetValue (ssl, null);
-		}
+			var certs = new X509CertificateCollection ();
+			var ssl = new SslStream (ns, false, (s, cert, chain, p) => {
+				var elements = chain?.ChainPolicy?.ExtraStore;
+				if (elements != null && elements.Count > 0) {
```
Comment (marek-safar) [inline mcs/tools/security/certmgr.cs]: btw, this could be `elements?.Count > 0`
