### PR TITLE
[debugger] Fix NOT_IMPLEMENTED while debugging.

### LINKED ISSUE #19146: Crash by hitting NOT_IMPLEMENTED assert during managed debugging
Note: I'm using the Unity debugger that's built into Visual Studio to connect here

https://issuetracker.unity3d.com/issues/crash-when-declaring-a-replacement-variable-with-using-that-encompasses-any-kind-of-dictionary

## Steps to Reproduce

1.  mcs -debug Program.cs
2. mono --debug --debugger-agent=transport=dt_socket,server=y,address=127.0.0.1:56900 Program.exe
3. Open Visual Studio -> Debug -> Attach Unity Debugger
4. Click "Input IP"
5. Input 127.0.0.1:56900 and press Ok
6. Put breakpoint on line 11 :: `int anyVariable = 0;`
7. Hit any key in terminal that mono was executed in to trigger breakpoint.
8. Hover on anyVariable. If this doesn't trigger the crash hover Main and then anyVariable again. It should be pretty quick to get the `CMD_ASSEMBLY_GET_TYPE` to trigger

```
using System;
using dictionaryReplacement = System.Collections.Generic.Dictionary<double, float>;

namespace DictionaryCrash
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.ReadLine();
            int anyVariable = 0;
        }
    }
}
```

### Current Behavior

```
>"C:\Program Files\Mono\bin\mono.exe" --debug --debugger-agent=transport=dt_socket,server=y,address=127.0.0.1:56900 Program.exe

* Assertion: should not be reached at ..\mono\mini\debugger-agent.c:7715
```

### Expected Behavior

No crash

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[x ] Windows

**Version Used**:
`Mono JIT compiler version 6.8.0 (Visual Studio built mono)`

### PR DESCRIPTION
**Pull request by thaystg**
- Changed mono_reflection_parse_type_checked to accept names that includes < and >
- Changed the behavior on debugger-agent, if we can't parse the new behavior is to return invalid_argument and not assert and stop debugging
- Changed the mono_domain_set_fast before return from assembly_commands.

Fixes #19146

### CODE REVIEW

**Comment by lambdageek** [comment]
I don't think this is the right approach. `_mono_reflection_parse_type` is meant to parse types in the format given to `Type.GetType(string)` https://docs.microsoft.com/en-us/dotnet/api/system.type.gettype?view=netframework-4.8#System_Type_GetType_System_String_

It looks like debugger-libs is sending us a type in the wrong format.

File: mono/mini/debugger-agent.c [hunk 1]
```diff
@@ -7755,13 +7755,18 @@ assembly_commands (int command, guint8 *p, guint8 *end, Buffer *buf)
...
 			t = NULL;
 		} else {
-			if (info.assembly.name)
-				NOT_IMPLEMENTED;
+			if (info.assembly.name) {
+				mono_reflection_free_type_info (&info);
+				g_free (s);
+				mono_domain_set_fast (d, TRUE);
+				return ERR_INVALID_ARGUMENT;
+			}
```
Comment (lambdageek) [inline mono/mini/debugger-agent.c]: This part seems reasonable

**Comment by vargaz** [comment]
ASSEMBLY_GET_TYPE is supposed to imitate Assembly.GetType (), so it shouldn't receive an assembly qualified type name.

File: mono/mini/debugger-agent.c (hunk 1 above)
Comment (thaystg) [reply mono/mini/debugger-agent.c]: I discussed with Jb Evain and he will investigate on Unity debugger side. So we should just remove the assert and return a invalid argument.

File: mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs [hunk 2]
```diff
@@ -810,6 +815,10 @@ class PacketReader {
 				get; set;
 			}
 
+			public string ErrorMsg {
+				get; set;
```
Comment (lambdageek) [inline mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs]:
```suggestion
				get; internal set;
```

File: mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/VirtualMachine.cs [hunk 3]
```diff
@@ -886,13 +886,18 @@ class EventHandler : MarshalByRefObject, IEventHandler
...
 			ErrorCode = error_code;
+			ErrorMessage = error_message;
 		}
 
 		public ErrorCode ErrorCode {
 			get; set;
 		}
+
+		public string ErrorMessage {
+			get; set;
```
Comment (lambdageek) [inline mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/VirtualMachine.cs]:
```suggestion
			get; internal set;
```

File: mono/mini/debugger-agent.c [hunk 4]
```diff
@@ -7740,6 +7740,8 @@ assembly_commands (int command, guint8 *p, guint8 *end, Buffer *buf)
 	case CMD_ASSEMBLY_GET_TYPE: {
 		ERROR_DECL (error);
 		char *s = decode_string (p, &p, end);
+		char* error_msg = g_strdup_printf ("Invalid assembly name \"%s\"", s);
```
Comment (lambdageek) [inline mono/mini/debugger-agent.c]:
```suggestion
		char* error_msg = g_strdup_printf ("Invalid type name \"%s\"", s);
```

File: mcs/class/Mono.Debugger.Soft/Test/dtest.cs [hunk 5]
```diff
@@ -5198,6 +5198,17 @@ public void Bug59649 ()
...
 
+	[Test]
+	public void InvalidArgumentAssemblyGetType () {
+		Event e = run_until ("test_invalid_argument_assembly_get_type");
+		var assembly = entry_point.DeclaringType.Assembly;
+		try {
+			var type = assembly.GetType ("System.Collections.Generic.Dictionary<double, float>.Main");
+		}
+		catch (CommandException ex) {
+			Assert.AreEqual(ex.ErrorMessage, "Invalid assembly name \"System.Collections.Generic.Dictionary<double, float>.Main\"");
```
Comment (lambdageek) [inline mcs/class/Mono.Debugger.Soft/Test/dtest.cs]:
```suggestion
			Assert.AreEqual(ex.ErrorMessage, "Invalid type name \"System.Collections.Generic.Dictionary<double, float>.Main\"");
```

File: mono/mini/debugger-agent.c [hunk 6]
```diff
@@ -7755,20 +7757,29 @@ assembly_commands (int command, guint8 *p, guint8 *end, Buffer *buf)
 			mono_error_cleanup (error);
 			t = NULL;
 		} else {
-			if (info.assembly.name)
-				NOT_IMPLEMENTED;
+			if (info.assembly.name) {
+				mono_reflection_free_type_info (&info);
+				g_free (s);
+				mono_domain_set_fast (d, TRUE);
+				buffer_add_string (buf, error_msg);
```
Comment (lambdageek) [inline mono/mini/debugger-agent.c]: nit: the error message for this case should be something like `"unexpected assembly-qualified type \"%s\" was provided"`

File: mono/mini/debugger-agent.c [hunk 7]
```diff
@@ -7755,20 +7757,29 @@ assembly_commands (int command, guint8 *p, guint8 *end, Buffer *buf)
...
+				g_free (error_msg);
+				return ERR_INVALID_ARGUMENT;
+			}
 			t = mono_reflection_get_type_checked (alc, ass->image, ass->image, &info, ignorecase, TRUE, &type_resolve, error);
 			if (!is_ok (error)) {
 				mono_error_cleanup (error); /* FIXME don't swallow the error */
 				mono_reflection_free_type_info (&info);
 				g_free (s);
+				mono_domain_set_fast (d, TRUE);
+				buffer_add_string (buf, error_msg);
```
Comment (lambdageek) [inline mono/mini/debugger-agent.c]: This one is ok.  In this case the type name really is invalid.

File: mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs (hunk 2 above)
Comment (lambdageek) [reply mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs]: I'm not 100% confident about my suggestion here (and the other `internal set`).  If it makes sense to keep this publicly writeable in the context of debugger-libs, please ignore.

File: mono/mini/debugger-agent.c (hunk 6 above)
Comment (thaystg) [reply mono/mini/debugger-agent.c]: Done

File: mono/mini/debugger-agent.c [hunk 8]
```diff
@@ -7825,6 +7841,7 @@ assembly_commands (int command, guint8 *p, guint8 *end, Buffer *buf)
         error_init (error);
         MonoClass* mono_class = mono_class_get_checked (ass->image, token, error);
         if (!is_ok (error)) {
+            buffer_add_string (buf, error->full_message);
```
Comment (lambdageek) [inline mono/mini/debugger-agent.c]:
```suggestion
            buffer_add_string (buf, mono_error_get_message (error));
```

`error->full_message` is not always the field with the complete message (see `mono_error_get_message` for details)

File: mono/mini/debugger-agent.c [hunk 9]
```diff
@@ -7841,6 +7858,7 @@ assembly_commands (int command, guint8 *p, guint8 *end, Buffer *buf)
         error_init (error);
         MonoMethod* mono_method = mono_get_method_checked (ass->image, token, NULL, NULL, error);
         if (!is_ok (error)) {
+            buffer_add_string (buf, error->full_message);
```
Comment (lambdageek) [inline mono/mini/debugger-agent.c]:
```suggestion
            buffer_add_string (buf, mono_error_get_message (error));
```

File: mono/mini/debugger-agent.c [hunk 10]
```diff
@@ -8693,6 +8711,7 @@ method_commands_internal (int command, MonoMethod *method, MonoDomain *domain, g
 
 		header = mono_method_get_header_checked (method, error);
 		if (!header) {
+			buffer_add_string (buf, error->full_message);
```
Comment (lambdageek) [inline mono/mini/debugger-agent.c]:
```suggestion
			buffer_add_string (buf, mono_error_get_message (error));
```

File: mono/mini/debugger-agent.c [hunk 11]
```diff
@@ -9524,7 +9543,7 @@ string_commands (int command, guint8 *p, guint8 *end, Buffer *buf)
 			if (!is_ok (error)) {
 				if (s)
 					g_free (s);
-
+				buffer_add_string (buf, error->full_message);
```
Comment (lambdageek) [inline mono/mini/debugger-agent.c]:
```suggestion
				buffer_add_string (buf, mono_error_get_message (error));
```

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
@monojenkins commit apidiff

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

File: mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs [hunk 12]
```diff
@@ -792,10 +795,12 @@ class PacketReader {
 
 				// For reply packets
 				offset = 0;
-				ReadInt (); // length
+				var len = ReadInt (); // length
 				ReadInt (); // id
 				ReadByte (); // flags
 				ErrorCode = ReadShort ();
+				if (ErrorCode == (int)Mono.Debugger.Soft.ErrorCode.INVALID_ARGUMENT && len > offset)
```
Comment (UnityAlex) [inline mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs]: Do we need a protocol bump for this? @thaystg

Comment (vargaz) [reply mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs]: I think len > offset takes care of it, but it would be nicer to do it with a protocol bump.

Comment (jbevain) [reply mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs]: Agreed with @vargaz.

Comment (thaystg) [reply mcs/class/Mono.Debugger.Soft/Mono.Debugger.Soft/Connection.cs]: I'm bumping the protocol but I still need to check with  len > offset  because I don't know if I inserted the error message everywhere that is needed.

**Comment by thaystg** [comment]
@monojenkins backport 2020-02
