### PR TITLE
Fix marshalling bugs for StringBuilder parameters

### LINKED ISSUE #15366: StringBuilder marshalling bug
## Steps to Reproduce

1. Compile:
```csharp
using System;
using System.Runtime.InteropServices;
using System.Text;

class Program
{
    [DllImport("user32.dll", CharSet = CharSet.Unicode)]
    static extern uint CharLowerBuffW([In, Out] StringBuilder lpsz, uint cchLength);

    static void Main()
    {
        var sb = new StringBuilder().AppendLine("HELLO").AppendLine("WORLD").AppendLine("FROM MONO");
        CharLowerBuffW(sb, (uint)sb.Length);
        Console.WriteLine(sb); // sb is corrupted/freed at this step
    }
}
```

### Expected Behavior

```
hello
world
from mono
```

### Actual Behavior

Segfault
or sometimes StringBuilder contains some random chars at the end after marshalling.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[x] Windows

### PR DESCRIPTION
**Pull request by filipnavara**
Fixes #15366 and #15306.

- Fixes NULL termination of `StringBuilder` to UTF-16 marshalling. Additionally an extra NULL is added as defense-in-depth protection for incorrect handling in native calls. This extra NULL adds protection when trying to marshal the NULL-terminated string back and the native function doesn't null-terminate at the size of the buffer.
- Fixes marshalling back from UTF-16/UTF-8 buffers into chunked `StringBuilder`.
- Fixes missing `mono_marshal_free` call causing a memory leak when marshalling `StringBuilder` to UTF-16 and back.
- Skips marshalling back to `StringBuilder` when the parameter doesn't have `[Out]` attribute.

Unit tests are still TBD. Not sure where to put them and how to structure them. Any help would be appreciated. /cc @vargaz @EgorBo

### CODE REVIEW

File: mono/metadata/marshal.c [hunk 1]
```diff
@@ -1358,11 +1383,6 @@ mono_marshal_get_ptr_to_stringbuilder_conv (MonoMethodPInvoke *piinfo, MonoMarsh
 
 	switch (encoding) {
 	case MONO_NATIVE_LPWSTR:
-		/* 
-		 * mono_string_builder_to_utf16 does not allocate a 
-		 * new buffer, so no need to free it.
-		 */
-		*need_free = FALSE;
```
Comment (filipnavara) [inline mono/metadata/marshal.c]: There are cases where we can skip the allocation in `mono_string_builder_to_utf16`. However, that is currently not done and hence the comment was wrong. I kept the `need_free` argument in case someone decides to optimize this code path later.

File: mono/metadata/marshal.c [hunk 2]
```diff
@@ -758,11 +758,33 @@ mono_string_builder_new (int starting_string_length, MonoError *error)
...
+			int charsToCopy = MIN (string_len - chunkOffset, maxLength);
+			memcpy (MONO_HANDLE_RAW (chunkChars)->vector, text + chunkOffset, charsToCopy * sizeof (gunichar2));
+			MONO_HANDLE_SETVAL (chunk, chunkLength, int, charsToCopy);
+		} else {
+			MONO_HANDLE_SETVAL (chunk, chunkLength, int, 0);
+		}
+		MONO_HANDLE_GET (chunk, chunk, chunkPrevious);
+	} while (MONO_HANDLE_BOOL (chunk));
+
+	MONO_EXIT_NO_SAFEPOINTS;
```
Comment (filipnavara) [inline mono/metadata/marshal.c]: This code is quite long and admittedly not easy to read. Alternative is to go in CoreCLR footsteps and rewrite the function to always spit out `StringBuilder` with single chunk.

File: mono/metadata/marshal-ilgen.c [hunk 3]
```diff
@@ -5483,7 +5483,7 @@ emit_marshal_object_ilgen (EmitMarshalContext *m, int argnum, MonoType *t,
 				}
 
 				mono_mb_emit_byte (mb, CEE_STIND_REF);
-			} else {
+			} else if (t->attrs & PARAM_ATTRIBUTE_OUT) {
```
Comment (filipnavara) [inline mono/metadata/marshal-ilgen.c]: It is both unnecessary and functionally wrong to marshal back the buffer contents. TBD: Check other places if the check is missing somewhere else too.

**Comment by CoffeeFlux** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@monojenkins backport 2019-06
