### PR TITLE
Fix SafeHandle marshalling in ref/in/out parameters

### LINKED ISSUE #17327: SafeHandle marshalling bug
Compile the following native code as a shared lib:
```c
#include <stdio.h>

void test2(void** ptr)
{
    printf("current vall: %p\n", *ptr);
    *ptr = (void*)0xDEADBEEF;
}
```
I used `gcc` on Ubuntu:
```
gcc -c -fPIC sht.c && gcc -shared -fPIC -Wl,-soname,libsht.so sht.o -o libsht.so -lc
```

Then run a C# code with pinvokes:
```csharp
using System;
using System.Runtime.InteropServices;

unsafe class Program
{
    [DllImport("sht", CallingConvention = CallingConvention.Cdecl)]
    public static extern void test2(void** ptr);
    
    // same pinvoke but with SafeHandle
    [DllImport("sht", CallingConvention = CallingConvention.Cdecl, EntryPoint = "test2")]
    public static extern void test2_sh(ref MySafeHandle ptr);
    
    static void Main(string[] args)
    {
        // raw pointers work:
        long ptr;
        test2((void**)&ptr); // prints (nil)
        test2((void**)&ptr); // prints (0xdeadbeef)

        // safehandle doesn't
        MySafeHandle handle = new MySafeHandle();
        test2_sh(ref handle); // prints (nil)
        test2_sh(ref handle); // prints (nil) -- but should be 0xdeadbeef!
    }
}

internal sealed class MySafeHandle : SafeHandle
{
    public MySafeHandle() : base(IntPtr.Zero, true) {}

    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        Console.WriteLine("ReleaseHandle()");
        SetHandle(IntPtr.Zero);
        return true;
    }
}
```

Output for .NET Core:
```
current vall: (nil)
current vall: 0xdeadbeef
current vall: (nil)
current vall: 0xdeadbee
```
Output for Mono:
```
current vall: (nil)
current vall: 0xdeadbeef
current vall: (nil)
current vall: (nil)
```
This is the main reason why NTLM/GSS/pal_gssapi.c stuff doesn't work properly and fail randomly.

### PR DESCRIPTION
**Pull request by filipnavara**
Fixes #17327

### CODE REVIEW

File: mono/metadata/marshal-ilgen.c [hunk 1]
```diff
@@ -5117,7 +5120,7 @@ emit_marshal_safehandle_ilgen (EmitMarshalContext *m, int argnum, MonoType *t,
 {
 	MonoMethodBuilder *mb = m->mb;
 	MonoType *int_type = mono_get_int_type ();
-	MonoType *boolean_type = m_class_get_byval_arg (mono_defaults.boolean_class);
+	MonoType *boolean_type = m_class_get_byval_arg (mono_defaults.boolean_class);
```
Comment (lambdageek) [inline mono/metadata/marshal-ilgen.c]: nit: whitespace

**Comment by filipnavara** [comment]
It currently fails the `test_0_safehandle_ref` test. I believe the test is incorrect but I will run it on different runtimes to see how it behaves.

File: mono/metadata/marshal-ilgen.c [hunk 2]
```diff
@@ -5182,35 +5199,61 @@ emit_marshal_safehandle_ilgen (EmitMarshalContext *m, int argnum, MonoType *t,
...
+				 * Create an empty SafeHandle (of correct derived type).
+				 * 
+				 * FIXME: If an out-of-memory situation or exception happens here we will
+				 * leak the handle. We should move the allocation of the SafeHandle to the
+				 * input marshalling code to prevent that.
+				 */
+				ctor = mono_class_get_method_from_name_checked (t->data.klass, ".ctor", 0, 0, error);
+				if (ctor == NULL || !is_ok (error)){
+					mono_mb_emit_exception (mb, "MissingMethodException", "paramterless constructor required");
+					mono_error_cleanup (error);
```
Comment (lambdageek) [inline mono/metadata/marshal-ilgen.c]: use a `local_error`, otherwise this will poison `error` if it is set later (by the caller, for example).  Something like:
```c
    ERROR_DECL (local_error);
    ctor = get_method (..., local_error);
    if (ctor == NULL || !is_ok (local_error)) {
        ...
        mono_error_cleanup (local_error);
    }
```

Comment (filipnavara) [reply mono/metadata/marshal-ilgen.c]: It is already local variable and the code is mostly unchanged from what was there before my change. I can rename it to `local_error` for additional clarity.

**Comment by filipnavara** [comment]
I agree more tests are in order. I'll look into it once I get positive results from the current CI run.

File: mono/metadata/marshal-ilgen.c (hunk 2 above)
Comment (lambdageek) [reply mono/metadata/marshal-ilgen.c]: Oh, sorry about that. Not sure what I looked at. This is fine, of course, if it's local

**Comment by filipnavara** [comment]
I added some tests for the fixed behavior. There's one CoreFX test I had to disable that is unrelated to the changes (upstream fix at https://github.com/dotnet/corefx/pull/41801).

**Comment by filipnavara** [comment]
@monojenkins build OS X x64 C++

**Comment by steveisok** [comment]
@monojenkins backport 2019-10

**Comment by steveisok** [comment]
@monojenkins backport 2019-08

**Comment by filipnavara** [comment]
@steveisok should I backport manually?

**Comment by steveisok** [comment]
Yeah, if you want to :-)

**Comment by steveisok** [comment]
Whoops... I guess I should hit refresh :-).  @filipnavara Thought you didn't get to it yet.
